if GetLocale() ~= "itIT" then
	return
end

local MOVANY = {
	ADD = "Aggiungi",
	ADDNEW = "Aggiugni nuovo",
	BINDING_NAME_EDIT_FRAME_EXACT = "Edit frame - Exact", -- Missing translation
	BINDING_NAME_EDIT_FRAME_SAFE = "Edit frame - Safe", -- Missing translation
	BINDING_NAME_HIDE_FRAME_EXACT = "Hide frame - Exact", -- Missing translation
	BINDING_NAME_HIDE_FRAME_SAFE = "Hide frame - Safe", -- Missing translation
	BINDING_NAME_MOVE_FRAME_EXACT = "Move frame - Exact", -- Missing translation
	BINDING_NAME_MOVE_FRAME_SAFE = "Move frame - Safe", -- Missing translation
	BINDING_NAME_RESET_FRAME_EXACT = "Reset frame - Exact", -- Missing translation
	BINDING_NAME_RESET_FRAME_SAFE = "Reset frame - Safe", -- Missing translation
	BINDING_NAME_SHOW_FRAME_INFO = "Show frame info", -- Missing translation
	BINDING_NAME_SYNCHRONIZE_ALL_ELEMENTS = "Synchronize all elements", -- Missing translation
	BINDING_NAME_TOGGLE_MA_WINDOW = "Toggle MA window", -- Missing translation
	CLOSEGUIONESC = "Il tasto esc chiude il menu principale",
	CMD_SYNTAX_DELETE = "Sintassi: /movedelete NomeProfilo",
	CMD_SYNTAX_EXPORT = "Sintassi: /moveexport NomeProfilo",
	CMD_SYNTAX_HIDE = "Sintassi: /hide NomeProfilo",
	CMD_SYNTAX_IMPORT = "Sintassi: /moveimport NomeProfilo",
	CMD_SYNTAX_MAFE = "Sintassi: /mafe nomeFinestra",
	CMD_SYNTAX_UNMOVE = "Sintassi: /unmove nomeFinestra",
	DELETE = "Cancella",
	DISABLED_DURING_COMBAT = "Disabilitato durante il combattimento",
	DISERRORMES = "Abilita o disabilita messaggi d'errore",
	DISERRORMESNO = "Disabilita messaggi d'errore",
	DONSEARCHFRAMENAME = "Disabilita la ricerca nei nomi delle finestre attuali",
	DONTSEARCH = "Non cercare nei nomi delle finestre",
	DONTSYNCINCOMBAT = "Abilita e disabilita se MoveAnything deve sincronizzare le finestre in coda lasciando il combattimento.\n\nDisabilitare questa opzione può causare una sincronizzazione manuale delle finestre protette quando lasci il combattimento.",
	DONTSYNCINCOMBATNO = "Disabilita sincronizzazione quando lasci il combattimento",
	ELEMENT_NOT_FOUND = "Elemento UI non trovato",
	ELEMENT_NOT_FOUND_NAMED = "Elemento UI non trovato: %s",
	ERROR_FRAME_FAILED = "Errore durante la sincronizzazione di %s. Reimposta la finestra e ricarica l'UI prima di modificarla nuovamente potrebbe risolvere il problema. Puoi disabilitare questo messaggio nelle opzioni. Se il problema persiste, per favore contatta l'autore con il seguente: %s %s %s",
	ERROR_MODULE_FAILED = "Errore durante l'aggiustamento di %s per %s. Puoi disabilitare questo messaggio nelle opzioni. Se il problema persiste, per favore contatta l'autore con il seguente: %s %s %s",
	ERROR_NOT_A_TABLE = "\"%s\" non è un tipo supportato",
	FE_FORCED_LOCK_POSITION_CONFIRM = "Forzare blocco posizione? Premi entro 5 secondi per confermare",
	FE_FORCED_LOCK_POSITION_TOOLTIP = "Sovrascrive l'ancoraggio dell'elemento,\nrimpiazzandolo con un punto bloccato\n\nPuò causare un errore se protetto,\ne può causare errori in combattimento\n\nRichiede un riavvio o un relog dopo aver\ndeselezionato per ripristinare l'ancoraggio originale",
	FE_GROUP_RESET_CONFIRM = "Reimpostare il gruppo %i? Premi entro 5 secondi per confermare",
	FE_GROUPS_TOOLTIP = "Gruppo %i",
	FE_UNREGISTER_ALL_EVENTS_CONFIRM = "Rimuovere tutti gli eventi? Premi entro 5 secondi per confermare",
	FE_UNREGISTER_ALL_EVENTS_TOOLTIP = "Rimuovere degli eventi della finestra,\nrende la finestra inerme\n\nRiabilitando la rimozione degli eventi richiede una ricarica dell'UI\noppure un relog dopo aver spuntato questa casella",
	FRAME_NO_FRAME_EDITOR = "L'editor delle finestre è disabilitato per %s",
	FRAME_ONLY_ONCE_OPENED = "Si può interagire con %s solo dopo che è stata mostrata",
	FRAME_ONLY_WHEN_BANK_IS_OPEN = "Si può interagire con %s quando la banca è aperta",
	FRAME_ONLY_WHEN_VOIDSTORAGE_IS_OPEN = "Si può interagire con %s quando è aperta",
	FRAME_PROTECTED_DURING_COMBAT = "Non si può interagire con %s durante il combattimento",
	FRAME_UNPOSITIONED = "%s non è posizionata e non si può muovere senza posizionamento",
	FRAME_VISIBILITY_ONLY = "%s può solo essere nascosta",
	HOOKALLOWED = "Abilita o disabilita se MoveAnything deve gestire CreateFrame.\n\nRichiede un riavvio per funzionare.",
	HOOKALLOWEDNO = "Disabilita gestione su nuove finestre",
	LIST_HEADING_CATEGORY_AND_FRAMES = "Categorie e Finestre",
	LIST_HEADING_HIDE = "Nascondi",
	LIST_HEADING_MOVER = "Mover",
	LIST_HEADING_SEARCH_RESULTS = "Risultati ricerca: %i",
	MA_OPT_ALWAYS_SHOW_NUDGER = "Show Nudger with main window", -- Missing translation
	MA_OPT_ALWAYS_SHOW_NUDGER_TOOLTIP = "Enable to show the nudger with the main window\n\nBy default the Nudger is only shown when interacting with frames.", -- Missing translation
	MA_OPT_CLOSE_GUI_ON_ESCAPE = "Escape key closes main window", -- Missing translation
	MA_OPT_DISABLE_ERROR_MESSAGES = "Disable error messages", -- Missing translation
	MA_OPT_DISABLE_ERROR_MESSAGES_TOOLTIP = "Toggles printing of error messages on/off.", -- Missing translation
	MA_OPT_DONT_HOOK_CREATE_FRAME = "Disable frame creation hook", -- Missing translation
	MA_OPT_DONT_HOOK_CREATE_FRAME_TOOLTIP = "Toggles if MoveAnything will hook CreateFrame.\n\nRequires reload to take effect.", -- Missing translation
	MA_OPT_DONT_SEARCH_FRAME_NAMES = "Don't search frame names", -- Missing translation
	MA_OPT_DONT_SEARCH_FRAME_NAMES_TOOLTIP = "Disables searching of actual frame names.", -- Missing translation
	MA_OPT_DONT_SYNC_WHEN_LEAVING_COMBAT = "Disable sync when leaving combat", -- Missing translation
	MA_OPT_DONT_SYNC_WHEN_LEAVING_COMBAT_TOOLTIP = "Toggles if MoveAnything will synchronize pending frames when leaving combat.\n\nDisabling this may result in protected frames requiring a manual sync when leaving combat.", -- Missing translation
	MA_OPT_EXPORT_PROFILE = "Export Profile", -- Missing translation
	MA_OPT_FRAME_LIST_ROWS = "List rows", -- Missing translation
	MA_OPT_IMPORT_PROFILE = "Import Profile", -- Missing translation
	MA_OPT_NO_BAGS = "Disable bag container hook", -- Missing translation
	MA_OPT_NO_BAGS_TOOLTIP = "Toggles if MoveAnything will hook containers.\n\nThis should be checked if you use another addon to move your bags.", -- Missing translation
	MA_OPT_NO_MMMW = "Disable Minimap mousewheel zoom", -- Missing translation
	MA_OPT_NO_MMMW_TOOLTIP = "Toggles Minimap mousewheel zoom on/off.\n\nRequires reload to take effect.", -- Missing translation
	MA_OPT_PLAY_SOUND = "Play sound", -- Missing translation
	MA_OPT_PLAY_SOUND_TOOLTIP = "Toggles if MoveAnything should play a sound when opening and closing the main window.", -- Missing translation
	MA_OPT_PROFILE = "Profile", -- Missing translation
	MA_OPT_PROFILE_ADD_TOOLTIP = "Add new", -- Missing translation
	MA_OPT_PROFILE_DELETE_TOOLTIP = "Delete", -- Missing translation
	MA_OPT_PROFILE_EXPORT = "Export", -- Missing translation
	MA_OPT_PROFILE_EXPORT_IMPORT_LABEL = "%s Profile", -- Missing translation
	MA_OPT_PROFILE_FROM = "From", -- Missing translation
	MA_OPT_PROFILE_IMPORT = "Import", -- Missing translation
	MA_OPT_PROFILE_NO_PROFILES = "No profiles available", -- Missing translation
	MA_OPT_PROFILE_PROFILE_NOT_MODIFIED = "No profile has modified this frame", -- Missing translation
	MA_OPT_PROFILE_PROFILE_NOT_MODIFIED_PLURAL = "No profiles has modified this frame", -- Missing translation
	MA_OPT_PROFILE_RENAME_TOOLTIP = "Rename", -- Missing translation
	MA_OPT_PROFILE_SAVE_AS_TOOLTIP = "Save as", -- Missing translation
	MA_OPT_PROFILE_TO = "To", -- Missing translation
	MA_OPT_RESET_ALL = "Reset All", -- Missing translation
	MA_OPT_RESET_ALL_TOOLTIP = "Reset all\n\nReset MoveAnything to default settings. Deletes all frame settings, as well as the custom frame list", -- Missing translation
	MA_OPT_RESET_PROFILE_TOOLTIP = "Reset profile\n\nResets the profile, deleting all stored frame settings for this profile.", -- Missing translation
	MA_OPT_ROWS_SLIDER = "# of rows", -- Missing translation
	MA_OPT_SHOW_TOOLTIPS = "Show tooltips", -- Missing translation
	MA_OPT_SHOW_TOOLTIPS_TOOLTIP = "Toggles display of tooltips on/off\n\nPressing Shift when mousing over elements will reverse tooltip display behavior.", -- Missing translation
	MA_OPT_SQUARE_MM = "Enable square Minimap", -- Missing translation
	MA_OPT_SQUARE_MM_TOOLTIP = "Toggles square MiniMap on/off.\n\nHide \"Round Border\" in the \"Minimap\" category to get rid of the overlaying border.", -- Missing translation
	MA_OPT_TEXT_STRING = "Text String", -- Missing translation
	MA_OPT_VERSION = "Version", -- Missing translation
	NO_NAMED_FRAMES_FOUND = "Nessun elemento nominato trovato",
	NOMMWP = "Abilita o disabilita lo zoom del mouse sulla Minimappa.\n\nRichiede un riavvio per funzionare.",
	NOMMWPNO = "Disabilita lo zoom del mouse sulla Minimappa",
	NUDGER1 = "Mostra Nudger con il menu principale",
	ONLY_ONCE_CREATED = "%s può solo essere modificato dopo che è stato creato",
	OPTBAGS1 = "Abilita o disabilita se MoveAnything deve gestire i contenitori.\n\nQuesto deve essere spuntato se usi un altro addon che muove le tue borse.",
	OPTBAGSTOOLTIP = "Disabilita gestione della borsa",
	OPTIONTOOLTIP1 = "Abilita per mostrare Nudger con il menu principale.\n\nDi default Nudger è mostrato solo quando interagisci con le finestre.",
	OPTIONTOOLTIP2 = "Abilita o disabilita display dei tooltip.\n\nTenendo premuto Shift sugli elementi inverte il comportamento del display dei tooltip.",
	PLAYSOUND = "Prova suono",
	PLAYSOUNDS = "Abilita o disabilita se MoveAnything deve suonare quando apri e chiudi il menu principale.",
	PROFILE_ADD_TEXT = "Inserisci un nuovo nome profilo",
	PROFILE_ALREADY_EXISTS = "Il profilo \"%s\" esiste già",
	PROFILE_CANT_DELETE_CURRENT_IN_COMBAT = "Non si può cancellare il profilo corrente durante il combattimento",
	PROFILE_CANT_DELETE_DEFAULT = "Il profilo di default non può essere cancellato",
	PROFILE_CURRENT = "Corrente",
	PROFILE_DELETE_TEXT = "Cancellare il profilo \"%s\"?",
	PROFILE_DELETED = "Profilo cancellato: %s",
	PROFILE_EXPORTED = "\"%s\" esportato a \"%s\"",
	PROFILE_IMPORTED = "\"%s\" è stato importato in \"%s\"",
	PROFILE_RENAME_TEXT = "Inserisci un nuovo nome per \"%s\"",
	PROFILE_RESET_CONFIRM = "MoveAnything: Reimpostare tutte le finestre del profilo corrente?",
	PROFILE_SAVE_AS_TEXT = "Inserisci un nuovo nome profilo",
	PROFILE_UNKNOWN = "Profilo sconosciuto: %s",
	PROFILES = "Profili",
	PROFILES_CANT_SWITCH_DURING_COMBAT = "I profili non posso essere modificati durante il combattimento",
	RENAME = "Rinomina",
	RESET_ALL_CONFIRM = "MoveAnything: Reimposto MoveAnything alle impostazioni di default?",
	RESET_FRAME_CONFIRM = "Reimposto %s? Premi entro 5 secondi per confermare",
	RESETALL1 = "Reimposta tutto.\n\nReimposta MoveAnything alle impostazioni di default. Cancella tutte le impostazioni delle finestre e la lista delle finestre personalizzate.",
	RESETPROFILE1 = "Reimposta profilo\n\nReimposta il profilo cancellando tutte le impostazioni delle finestre salvate per questo profilo.",
	RESETTING_FRAME = "Reimposto %s",
	SAVE = "Salva",
	SAVEAS = "Salva come",
	SEARCH_TEXT = "Cerca",
	SHOWTOOLTIPS = "Mostra tooltips",
	SQUARMAP = "Abilita o disabilita quadrato Minimappa\n\nNascondi i \"Bordi Arrotondati\" nella categoria \"Minimappa\" per rimuovere la sovrapposizione del bordo.",
	SQUARMAPNO = "Abilita Minimappa quadrata",
	UNSERIALIZE_FRAME_INVALID_FORMAT = "Formato invalido",
	UNSERIALIZE_FRAME_NAME_DIFFERS = "Il nome della finestra importata è diverso da quella di destinazione",
	UNSERIALIZE_PROFILE_COMPLETED = "Importati %i elemento/i nel profilo \"%s\"",
	UNSERIALIZE_PROFILE_NO_NAME = "Impossibile localizzare il nome profilo",
	UNSUPPORTED_FRAME = "Finestre non supportate: %s",
	UNSUPPORTED_TYPE = "Tipi non supportati: %s"
}

_G.MOVANY = MOVANY
