if GetLocale() ~= "esES" and GetLocale() ~= "esMX" then
	return
end

local MOVANY = {
	ADD = "Añade",
	ADDNEW = "Añadir nuevo",
	BINDING_NAME_EDIT_FRAME_EXACT = "Edit frame - Exact", -- Missing translation
	BINDING_NAME_EDIT_FRAME_SAFE = "Edit frame - Safe", -- Missing translation
	BINDING_NAME_HIDE_FRAME_EXACT = "Hide frame - Exact", -- Missing translation
	BINDING_NAME_HIDE_FRAME_SAFE = "Hide frame - Safe", -- Missing translation
	BINDING_NAME_MOVE_FRAME_EXACT = "Move frame - Exact", -- Missing translation
	BINDING_NAME_MOVE_FRAME_SAFE = "Move frame - Safe", -- Missing translation
	BINDING_NAME_RESET_FRAME_EXACT = "Reset frame - Exact", -- Missing translation
	BINDING_NAME_RESET_FRAME_SAFE = "Reset frame - Safe", -- Missing translation
	BINDING_NAME_SHOW_FRAME_INFO = "Show frame info", -- Missing translation
	BINDING_NAME_SYNCHRONIZE_ALL_ELEMENTS = "Synchronize all elements", -- Missing translation
	BINDING_NAME_TOGGLE_MA_WINDOW = "Toggle MA window", -- Missing translation
	CLOSEGUIONESC = "Tecla Escape cierra la ventana principal",
	CMD_SYNTAX_DELETE = "Sintaxis: /movedelete NombredelPerfil",
	CMD_SYNTAX_EXPORT = "Sintaxis: /moveexport NombredelPErfil",
	CMD_SYNTAX_HIDE = "Sintaxis: /hide NombredelPerfil",
	CMD_SYNTAX_IMPORT = "Sintaxis:/moveimport NombredelPerfil",
	CMD_SYNTAX_MAFE = "Sintaxis: /mafe Nombredelcuadro",
	CMD_SYNTAX_UNMOVE = "Sintaxis: /unmove Nombredelcuadro",
	DELETE = "Borrar",
	DISABLED_DURING_COMBAT = "Deshabilitado durante el combate",
	DISERRORMES = "Cambia impresión de los mensajes de error on/off.",
	DISERRORMESNO = "Desactivar los mensajes de error",
	DONSEARCHFRAMENAME = "Desactiva la búsqueda de nombres de marcos actuales.",
	DONTSEARCH = "No buscar los nombres de marcos",
	DONTSYNCINCOMBAT = "Cambia si MoveAnything sincronizara los marcos pendientes al salir de combate.\n\nDeshabilitar esto puede resultar en marcos protegidos que requieran una sincronización manual al salir de combate.",
	DONTSYNCINCOMBATNO = "Desactivar sincronización al salir de combate",
	ELEMENT_NOT_FOUND = "Elemento de interfaz de usuario que no se encuentra",
	ELEMENT_NOT_FOUND_NAMED = "Elemento de interfaz de usuario no encontrado: %s",
	ERROR_FRAME_FAILED = "Se produjo un error al sincronizar %s. Reiniciar el marco y volver a cargar antes de modificarlo de nuevo podría resolver el problema. Puede deshabilitar este mensaje en las opciones. Si el problema persiste, por favor informar lo siguiente al autor: %s %s %s",
	ERROR_MODULE_FAILED = "Ha ocurrido un error mientras se ajusta %s para %s. Puede deshabilitar este mensaje en las opciones. Si el problema persiste, por favor informa del siguiente al autor: %s %s %s %s",
	ERROR_NOT_A_TABLE = "\"%s\" es un tipo no soportado",
	FE_FORCED_LOCK_POSITION_CONFIRM = "Forzar bloqueo de la posición? Haga clic de nuevo dentro de 5 segundos para confirmar",
	FE_FORCED_LOCK_POSITION_TOOLTIP = "Sobrescribe método del elemento SetPoint,\nreemplazándolo con un código auxiliar vacío\n\nPuede causar una corrupción si el elemento está protegido\ny el código auxiliar se llama durante el combate\n\nRequiere volver a cargar o relog después de deseleccionarlo para\nrestablecer el método original de SetPoint",
	FE_GROUP_RESET_CONFIRM = "¿Restablecer Grupo  %i ? Haga clic de nuevo dentro de 5 segundos para confirmar",
	FE_GROUPS_TOOLTIP = "Grupo %i",
	FE_UNREGISTER_ALL_EVENTS_CONFIRM = "Anular el registro de todos los eventos? Haga clic de nuevo dentro de 5 segundos para confirmar",
	FE_UNREGISTER_ALL_EVENTS_TOOLTIP = "Anula el registro de los eventos que el marco está escuchando,\ndibujando la imagen inerte\n\nVolver a habilitar los eventos registrados requerirá volver a cargar\nrelog o después de deseleccionar la casilla de verificación",
	FRAME_NO_FRAME_EDITOR = "Editores de Marco está desactivado para %s",
	FRAME_ONLY_ONCE_OPENED = "Sólo puede interactuar con %s una vez se ha mostrado",
	FRAME_ONLY_WHEN_BANK_IS_OPEN = "sólo puede interactúar con %s mientras el banco está abierto",
	FRAME_ONLY_WHEN_VOIDSTORAGE_IS_OPEN = "Sólo puede interactuar %s está abierto",
	FRAME_PROTECTED_DURING_COMBAT = "No puede interactuar con %s durante el combate",
	FRAME_UNPOSITIONED = "%s está actualmente no posicionado y no se puede mover hasta que esté",
	FRAME_VISIBILITY_ONLY = "%s sólo se puede ocultar",
	HOOKALLOWED = "Habilita si MoveAnything fijará Crear marco.\n\nRequiere recargar para tener efecto.",
	HOOKALLOWEDNO = "Desactivar fijación de la creación de marco",
	LIST_HEADING_CATEGORY_AND_FRAMES = "Categorías y Marcos",
	LIST_HEADING_HIDE = "Oculta",
	LIST_HEADING_MOVER = "Encabezado Mover",
	LIST_HEADING_SEARCH_RESULTS = "Resultados de la búsqueda: %i",
	MA_OPT_ALWAYS_SHOW_NUDGER = "Show Nudger with main window", -- Missing translation
	MA_OPT_ALWAYS_SHOW_NUDGER_TOOLTIP = "Enable to show the nudger with the main window\n\nBy default the Nudger is only shown when interacting with frames.", -- Missing translation
	MA_OPT_CLOSE_GUI_ON_ESCAPE = "Escape key closes main window", -- Missing translation
	MA_OPT_DISABLE_ERROR_MESSAGES = "Disable error messages", -- Missing translation
	MA_OPT_DISABLE_ERROR_MESSAGES_TOOLTIP = "Toggles printing of error messages on/off.", -- Missing translation
	MA_OPT_DONT_HOOK_CREATE_FRAME = "Disable frame creation hook", -- Missing translation
	MA_OPT_DONT_HOOK_CREATE_FRAME_TOOLTIP = "Toggles if MoveAnything will hook CreateFrame.\n\nRequires reload to take effect.", -- Missing translation
	MA_OPT_DONT_SEARCH_FRAME_NAMES = "Don't search frame names", -- Missing translation
	MA_OPT_DONT_SEARCH_FRAME_NAMES_TOOLTIP = "Disables searching of actual frame names.", -- Missing translation
	MA_OPT_DONT_SYNC_WHEN_LEAVING_COMBAT = "Disable sync when leaving combat", -- Missing translation
	MA_OPT_DONT_SYNC_WHEN_LEAVING_COMBAT_TOOLTIP = "Toggles if MoveAnything will synchronize pending frames when leaving combat.\n\nDisabling this may result in protected frames requiring a manual sync when leaving combat.", -- Missing translation
	MA_OPT_EXPORT_PROFILE = "Export Profile", -- Missing translation
	MA_OPT_FRAME_LIST_ROWS = "List rows", -- Missing translation
	MA_OPT_IMPORT_PROFILE = "Import Profile", -- Missing translation
	MA_OPT_NO_BAGS = "Disable bag container hook", -- Missing translation
	MA_OPT_NO_BAGS_TOOLTIP = "Toggles if MoveAnything will hook containers.\n\nThis should be checked if you use another addon to move your bags.", -- Missing translation
	MA_OPT_NO_MMMW = "Disable Minimap mousewheel zoom", -- Missing translation
	MA_OPT_NO_MMMW_TOOLTIP = "Toggles Minimap mousewheel zoom on/off.\n\nRequires reload to take effect.", -- Missing translation
	MA_OPT_PLAY_SOUND = "Play sound", -- Missing translation
	MA_OPT_PLAY_SOUND_TOOLTIP = "Toggles if MoveAnything should play a sound when opening and closing the main window.", -- Missing translation
	MA_OPT_PROFILE = "Profile", -- Missing translation
	MA_OPT_PROFILE_ADD_TOOLTIP = "Add new", -- Missing translation
	MA_OPT_PROFILE_DELETE_TOOLTIP = "Delete", -- Missing translation
	MA_OPT_PROFILE_EXPORT = "Export", -- Missing translation
	MA_OPT_PROFILE_EXPORT_IMPORT_LABEL = "%s Profile", -- Missing translation
	MA_OPT_PROFILE_FROM = "From", -- Missing translation
	MA_OPT_PROFILE_IMPORT = "Import", -- Missing translation
	MA_OPT_PROFILE_NO_PROFILES = "No profiles available", -- Missing translation
	MA_OPT_PROFILE_PROFILE_NOT_MODIFIED = "No profile has modified this frame", -- Missing translation
	MA_OPT_PROFILE_PROFILE_NOT_MODIFIED_PLURAL = "No profiles has modified this frame", -- Missing translation
	MA_OPT_PROFILE_RENAME_TOOLTIP = "Rename", -- Missing translation
	MA_OPT_PROFILE_SAVE_AS_TOOLTIP = "Save as", -- Missing translation
	MA_OPT_PROFILE_TO = "To", -- Missing translation
	MA_OPT_RESET_ALL = "Reset All", -- Missing translation
	MA_OPT_RESET_ALL_TOOLTIP = "Reset all\n\nReset MoveAnything to default settings. Deletes all frame settings, as well as the custom frame list", -- Missing translation
	MA_OPT_RESET_PROFILE_TOOLTIP = "Reset profile\n\nResets the profile, deleting all stored frame settings for this profile.", -- Missing translation
	MA_OPT_ROWS_SLIDER = "# of rows", -- Missing translation
	MA_OPT_SHOW_TOOLTIPS = "Show tooltips", -- Missing translation
	MA_OPT_SHOW_TOOLTIPS_TOOLTIP = "Toggles display of tooltips on/off\n\nPressing Shift when mousing over elements will reverse tooltip display behavior.", -- Missing translation
	MA_OPT_SQUARE_MM = "Enable square Minimap", -- Missing translation
	MA_OPT_SQUARE_MM_TOOLTIP = "Toggles square MiniMap on/off.\n\nHide \"Round Border\" in the \"Minimap\" category to get rid of the overlaying border.", -- Missing translation
	MA_OPT_TEXT_STRING = "Text String", -- Missing translation
	MA_OPT_VERSION = "Version", -- Missing translation
	NO_NAMED_FRAMES_FOUND = "No se encontraron los elementos nombrados",
	NOMMWP = "Cambia zoom con rueda del ratón del minimapa  on/off.\n\nRequiere recargar para tener efecto.",
	NOMMWPNO = "Deshabilitar zoom con la rueda del ratón del minimapa ",
	NUDGER1 = "Mostrar Recordatorio con la ventana principal",
	ONLY_ONCE_CREATED = "%s sólo puede ser modificado después de que ha sido creado",
	OPTBAGS1 = "Cambia si se fijan los contenedores.\n\nEsto se debe revisar si se utiliza otro addon para mover sus bolsas.",
	OPTBAGSTOOLTIP = "Deshabilitar fijación de bolsas contenedoras",
	OPTIONTOOLTIP1 = "Activar para mostrar el Recordatorio con la ventana principal\n\nPor defecto, el Recordatorio sólo se muestra cuando se interactúa con los marcos.",
	OPTIONTOOLTIP2 = "Alterna la presentación de información de herramientas on/off\n\nSi pulsa Mayús al pasar el ratón sobre los elementos invertirá el comportamiento de información de herramientas de visualización.",
	PLAYSOUND = "Reproducir sonido",
	PLAYSOUNDS = "cambia si MoveAnything debe reproducir un sonido al abrir y cerrar la ventana principal.",
	PROFILE_ADD_TEXT = "Introduzca nuevo nombre de perfil",
	PROFILE_ALREADY_EXISTS = "Perfil  \"%s\" ya existe",
	PROFILE_CANT_DELETE_CURRENT_IN_COMBAT = "No se puede eliminar el perfil actual durante el combate",
	PROFILE_CANT_DELETE_DEFAULT = "El perfil por defecto no se puede eliminar",
	PROFILE_CURRENT = "Perfil Actual",
	PROFILE_DELETE_TEXT = "¿Borrar Perfil \"%s\"?",
	PROFILE_DELETED = "Perfil borrado: %s",
	PROFILE_EXPORTED = "\"%s\" exportado a \"%s\"",
	PROFILE_IMPORTED = "\"%s\" ha sido importado a \"%s\"",
	PROFILE_RENAME_TEXT = "Escribe nuevo nomre para \"%s\"",
	PROFILE_RESET_CONFIRM = "MoveAnything: Borrar todos los cuadros en el perfil actual?",
	PROFILE_SAVE_AS_TEXT = "Escriba nuevo nombre del perfil",
	PROFILE_UNKNOWN = "Perfil Desconocido: %s",
	PROFILES = "Perfiles",
	PROFILES_CANT_SWITCH_DURING_COMBAT = "Los perfiles no se pueden cambiar durante el combate",
	RENAME = "Renombrar",
	RESET_ALL_CONFIRM = "MoveAnything: Restablecer MoveAnything al estado de instalación?\n\nAdvertencia: esto eliminará todos los ajustes del marco y vaciar á la lista marco personalizado.",
	RESET_FRAME_CONFIRM = "Restaurar %s? Pulse de nuevo el plazo de 5 segundos para confirmar",
	RESETALL1 = "Restablecer todo\n\nRestablecer a la configuración predeterminada. Borra todas las configuraciones de marco, así como la lista de marco personalizado",
	RESETPROFILE1 = "Restaurar el perfil\n\nRestablece el perfil, borrar todos los ajustes almacenados marco para este perfil.",
	RESETTING_FRAME = "Restableciendo %s",
	SAVE = "Guadar",
	SAVEAS = "Guardar como",
	SEARCH_TEXT = "Buscar",
	SHOWTOOLTIPS = "Mostar información de herramientas.",
	SQUARMAP = "Cambia MiniMap cuadrado on/off.\n\nOculta \"Borde Redondo\" en el \"minimapa\" categoría para deshacerse de la superposición.de el borde ",
	SQUARMAPNO = "habilitar Minimpa Cuadrado",
	UNSERIALIZE_FRAME_INVALID_FORMAT = "Formato invalido",
	UNSERIALIZE_FRAME_NAME_DIFFERS = "Nombre Importado marco difiere de destino de importación",
	UNSERIALIZE_PROFILE_COMPLETED = "Importado %i elemento(s) en perfil \"% s\"",
	UNSERIALIZE_PROFILE_NO_NAME = "No se encuentra el nombre del perfil",
	UNSUPPORTED_FRAME = "Marco no soportado: %s",
	UNSUPPORTED_TYPE = "tipo no soportado: %s"
}

_G.MOVANY = MOVANY
