if GetLocale() ~= "enUS" and GetLocale() ~= "enGB" then
	return
end

local MOVANY = {
	ABSOLUTE_VALUES = "Absolute values",
	ADD = "Add",
	ADDNEW = "Add new",
	ALPHA = "Alpha",
	ARTWORK = "Artwork",
	ATTACH = "Attach",
	BACKGROUND = "Background",
	BINDING_NAME_EDIT_FRAME_EXACT = "Edit frame - Exact",
	BINDING_NAME_EDIT_FRAME_SAFE = "Edit frame - Safe",
	BINDING_NAME_HIDE_FRAME_EXACT = "Hide frame - Exact",
	BINDING_NAME_HIDE_FRAME_SAFE = "Hide frame - Safe",
	BINDING_NAME_MOVE_FRAME_EXACT = "Move frame - Exact",
	BINDING_NAME_MOVE_FRAME_SAFE = "Move frame - Safe",
	BINDING_NAME_RESET_FRAME_EXACT = "Reset frame - Exact",
	BINDING_NAME_RESET_FRAME_SAFE = "Reset frame - Safe",
	BINDING_NAME_SHOW_FRAME_INFO = "Show frame info",
	BINDING_NAME_SYNCHRONIZE_ALL_ELEMENTS = "Synchronize all elements",
	BINDING_NAME_TOGGLE_MA_WINDOW = "Toggle MA window",
	BORDER = "Border",
	CAN_BE_SCALED_LABEL = "W: %s H: %s",
	CAT_ACHIEVEMENTS_QUESTS = "Achievements & Quests",
	CAT_ARENA = "Arena",
	CAT_BATTLEGROUNDS_PVP = "Battlegrounds & PvP",
	CAT_BLIZZARD_ACTION_BARS = "Blizzard Action Bars",
	CAT_BLIZZARD_BAGS = "Blizzard Bags",
	CAT_BLIZZARD_BANK_AND_VOID_STORAGE = "Blizzard Bank and VoidStorage",
	CAT_BLIZZARD_BOTTOM_BAR = "Blizzard Bottom Bar",
	CAT_BOSS_SPECIFIC_FRAMES = "Boss Specific Frames",
	CAT_CLASS_SPECIFIC = "Class Specific",
	CAT_CUSTOM_FRAMES = "Custom Frames",
	CAT_DUNGEONS_RAIDS = "Dungeons & Raids",
	CAT_GAME_MENU = "Game Menu",
	CAT_GARRISON = "Garrison",
	CAT_GUILD = "Guild",
	CAT_INFO_PANELS = "Info Panels",
	CAT_LOOT = "Loot",
	CAT_MA_INTERNAL_ELEMENTS = "MA Internal Elements",
	CAT_MAP = "Map",
	CAT_MINIMAP = "Minimap",
	CAT_MISCELLANEOUS = "Miscellaneous",
	CAT_MOVE_ANYTHING = "MoveAnything",
	CAT_ORDER_HALL = "Order Hall",
	CAT_PET_BATTLE = "PetBattle",
	CAT_SHIPYARD = "Shipyard",
	CAT_STORE = "Store",
	CAT_UNIT_FOCUS = "Unit: Focus",
	CAT_UNIT_PARTY = "Unit: Party",
	CAT_UNIT_PET = "Unit: Pet",
	CAT_UNIT_PLAYER = "Unit: Player",
	CAT_UNIT_TARGET = "Unit: Target",
	CAT_VEHICLE = "Vehicle",
	CLAMP_TO_SCREEN = "Clamp to screen",
	CLOSEGUIONESC = "Escape key closes main window",
	CMD_SYNTAX_DELETE = "Syntax: /movedelete ProfileName",
	CMD_SYNTAX_EXPORT = "Syntax: /moveexport ProfileName",
	CMD_SYNTAX_HIDE = "Syntax: /hide ProfileName",
	CMD_SYNTAX_IMPORT = "Syntax: /moveimport ProfileName",
	CMD_SYNTAX_MAFE = "Syntax: /mafe frameName",
	CMD_SYNTAX_UNMOVE = "Syntax: /unmove frameName",
	DELETE = "Delete",
	DISABLED_DURING_COMBAT = "Disabled during combat",
	DISERRORMES = "Toggles printing of error messages on/off.",
	DISERRORMESNO = "Disable error messages",
	DONSEARCHFRAMENAME = "Disables searching of actual frame names.",
	DONTSEARCH = "Dont search frame names",
	DONTSYNCINCOMBAT = "Toggles if MoveAnything will synchronize pending frames when leaving combat.\n\nDisabling this may result in protected frames requiring a manual sync when leaving combat.",
	DONTSYNCINCOMBATNO = "Disable sync when leaving combat",
	EL_ACHIEVEMENT_ALERT_FRAME1 = "Achievement Alert 1", -- Missing translation
	EL_ACHIEVEMENT_ALERT_FRAME2 = "Achievement Alert 2", -- Missing translation
	EL_ACTION_BAR_DOWN_BUTTON = "Action Bar Page Down", -- Missing translation
	EL_ACTION_BAR_UP_BUTTON = "Action Bar Page Up", -- Missing translation
	EL_ACTION_STAUS = "Action Staus", -- Missing translation
	EL_ALERT_FRAME = "Alerts Frames", -- Missing translation
	EL_ALWAYS_UP_FRAME1 = "AlwaysUp Frame 1", -- Missing translation
	EL_ALWAYS_UP_FRAME2 = "AlwaysUp Frame 2", -- Missing translation
	EL_ALWAYS_UP_FRAME3 = "AlwaysUp Frame 3", -- Missing translation
	EL_ARCHAEOLOGY_FRAME = "Archaeology", -- Missing translation
	EL_ARCHEOLOGY_DIGSITE_PROGRESS_BAR = "Archeology Digsite ProgressBar", -- Missing translation
	EL_ARENA_ENEMY_FRAME1 = "Arena Enemy 1", -- Missing translation
	EL_ARENA_ENEMY_FRAME1_CASTING_BAR = "Arena Enemy Casting Bar 1", -- Missing translation
	EL_ARENA_ENEMY_FRAME1_PET_FRAME = "Arena Enemy Pet 1", -- Missing translation
	EL_ARENA_ENEMY_FRAME2 = "Arena Enemy 2", -- Missing translation
	EL_ARENA_ENEMY_FRAME2_CASTING_BAR = "Arena Enemy Casting Bar 2", -- Missing translation
	EL_ARENA_ENEMY_FRAME2_PET_FRAME = "Arena Enemy Pet 2", -- Missing translation
	EL_ARENA_ENEMY_FRAME3 = "Arena Enemy 3", -- Missing translation
	EL_ARENA_ENEMY_FRAME3_CASTING_BAR = "Arena Enemy Casting Bar 3", -- Missing translation
	EL_ARENA_ENEMY_FRAME3_PET_FRAME = "Arena Enemy Pet 3", -- Missing translation
	EL_ARENA_ENEMY_FRAME4 = "Arena Enemy 4", -- Missing translation
	EL_ARENA_ENEMY_FRAME4_CASTING_BAR = "Arena Enemy Casting Bar 4", -- Missing translation
	EL_ARENA_ENEMY_FRAME4_PET_FRAME = "Arena Enemy Pet 4", -- Missing translation
	EL_ARENA_ENEMY_FRAME5 = "Arena Enemy 5", -- Missing translation
	EL_ARENA_ENEMY_FRAME5_CASTING_BAR = "Arena Enemy Casting Bar 5", -- Missing translation
	EL_ARENA_ENEMY_FRAME5_PET_FRAME = "Arena Enemy Pet 5", -- Missing translation
	EL_ARENA_ENEMY_FRAMES = "ArenaEnemyFrames", -- Missing translation
	EL_ARENA_FRAME = "Arena Queue List", -- Missing translation
	EL_ARENA_PREP_FRAME1 = "Arena Prep 1", -- Missing translation
	EL_ARENA_PREP_FRAME2 = "Arena Prep 2", -- Missing translation
	EL_ARENA_PREP_FRAME3 = "Arena Prep 3", -- Missing translation
	EL_ARENA_PREP_FRAME4 = "Arena Prep 4", -- Missing translation
	EL_ARENA_PREP_FRAME5 = "Arena Prep 5", -- Missing translation
	EL_ARENA_PREP_FRAMES = "ArenaPrepFrames", -- Missing translation
	EL_ARENA_REGISTRAR_FRAME = "Arena Registrar", -- Missing translation
	EL_ARTIFACT_FRAME = "Artifact Frame", -- Missing translation
	EL_ARTIFACT_WATCH_BAR = "Artifact Bar", -- Missing translation
	EL_AUCTION_FRAME = "Auction House", -- Missing translation
	EL_AUCTION_PROGRESS_FRAME = "Auction Creation Progress", -- Missing translation
	EL_AUDIO_OPTIONS_FRAME = "Sound & Voice Options", -- Missing translation
	EL_BAG_BUTTONS_MOVER = "Bag Buttons", -- Missing translation
	EL_BAG_BUTTONS_VERTICAL_MOVER = "Bag Buttons - Vertical", -- Missing translation
	EL_BAG_FRAME1 = "Backpack", -- Missing translation
	EL_BAG_FRAME2 = "Bag 1", -- Missing translation
	EL_BAG_FRAME3 = "Bag 2", -- Missing translation
	EL_BAG_FRAME4 = "Bag 3", -- Missing translation
	EL_BAG_FRAME5 = "Bag 4", -- Missing translation
	EL_BAG_ITEM_AUTO_SORT_BUTTON = "Clean Up Bags", -- Missing translation
	EL_BAG_ITEM_SEARCH_BOX = "Bag Item Search", -- Missing translation
	EL_BAG_ITEM_TOOLTIP_MOVER = "Tooltip - Bag Item", -- Missing translation
	EL_BAGS_MOVER = "All Bags", -- Missing translation
	EL_BANK_BAG_FRAME1 = "Bank Bag 1", -- Missing translation
	EL_BANK_BAG_FRAME2 = "Bank Bag 2", -- Missing translation
	EL_BANK_BAG_FRAME3 = "Bank Bag 3", -- Missing translation
	EL_BANK_BAG_FRAME4 = "Bank Bag 4", -- Missing translation
	EL_BANK_BAG_FRAME5 = "Bank Bag 5", -- Missing translation
	EL_BANK_BAG_FRAME6 = "Bank Bag 6", -- Missing translation
	EL_BANK_BAG_FRAME7 = "Bank Bag 7", -- Missing translation
	EL_BANK_BAG_ITEMS_MOVER = "Bank Bag Items", -- Missing translation
	EL_BANK_BAG_SLOTS_MOVER = "Bank Bag Slots", -- Missing translation
	EL_BANK_FRAME = "Bank", -- Missing translation
	EL_BANK_FRAME_BAG1 = "Bank Bag Slot 1", -- Missing translation
	EL_BANK_FRAME_BAG2 = "Bank Bag Slot 2", -- Missing translation
	EL_BANK_FRAME_BAG3 = "Bank Bag Slot 3", -- Missing translation
	EL_BANK_FRAME_BAG4 = "Bank Bag Slot 4", -- Missing translation
	EL_BANK_FRAME_BAG5 = "Bank Bag Slot 5", -- Missing translation
	EL_BANK_FRAME_BAG6 = "Bank Bag Slot 6", -- Missing translation
	EL_BANK_FRAME_BAG7 = "Bank Bag Slot 7", -- Missing translation
	EL_BANK_FRAME_MONEY_FRAME = "Bank Money", -- Missing translation
	EL_BANK_FRAME_MONEY_FRAME_BORDER = "Bank Money Border", -- Missing translation
	EL_BANK_FRAME_MONEY_FRAME_COPPER_BUTTON = "Bank Money Copper", -- Missing translation
	EL_BANK_FRAME_MONEY_FRAME_GOLD_BUTTON = "Bank Money Gold", -- Missing translation
	EL_BANK_FRAME_MONEY_FRAME_INSET = "Bank Money Inset", -- Missing translation
	EL_BANK_FRAME_MONEY_FRAME_SILVER_BUTTON = "Bank Money Silver", -- Missing translation
	EL_BANK_ITEM_AUTO_SORT_BUTTON = "Bank Cleanup", -- Missing translation
	EL_BANK_ITEM_SEARCH_BOX = "Bank Item Search", -- Missing translation
	EL_BARBER_SHOP_FRAME = "Barber Shop", -- Missing translation
	EL_BASIC_ACTION_BUTTONS_MOVER = "Action Bar", -- Missing translation
	EL_BASIC_ACTION_BUTTONS_VERTICAL_MOVER = "Action Bar - Vertical", -- Missing translation
	EL_BATTLE_PET_TOOLTIP = "BattlePetTooltip", -- Missing translation
	EL_BATTLEFIELD_FRAME = "Battleground Queue", -- Missing translation
	EL_BATTLEFIELD_MINIMAP = "Battlefield Mini Map", -- Missing translation
	EL_BATTLEFIELD_MINIMAP = "Zone Minimap", -- Missing translation
	EL_BLACK_MARKET_FRAME = "Black Market Auction", -- Missing translation
	EL_BN_TOAST_FRAME = "Battle.Net Popup Message", -- Missing translation
	EL_BONUS_ROLL_FRAME = "Bonus Roll Frame", -- Missing translation
	EL_BONUS_ROLL_LOOT_WON_FRAME = "BonusRoll Item Won", -- Missing translation
	EL_BONUS_ROLL_MONEY_WON_FRAME = "BonusRoll Money Won", -- Missing translation
	EL_BOSS_BANNER = "Boss Banner", -- Missing translation
	EL_BOSS1_TARGET_FRAME = "Raid Boss Health Bar 1", -- Missing translation
	EL_BOSS1_TARGET_FRAME_POWER_BAR_ALT = "Raid Boss Power Bar 1", -- Missing translation
	EL_BOSS2_TARGET_FRAME = "Raid Boss Health Bar 2", -- Missing translation
	EL_BOSS2_TARGET_FRAME_POWER_BAR_ALT = "Raid Boss Power Bar 2", -- Missing translation
	EL_BOSS3_TARGET_FRAME = "Raid Boss Health Bar 3", -- Missing translation
	EL_BOSS3_TARGET_FRAME_POWER_BAR_ALT = "Raid Boss Power Bar 3", -- Missing translation
	EL_BOSS4_TARGET_FRAME = "Raid Boss Health Bar 4", -- Missing translation
	EL_BOSS4_TARGET_FRAME_POWER_BAR_ALT = "Raid Boss Power Bar 4", -- Missing translation
	EL_BOSS5_TARGET_FRAME = "Raid Boss Health Bar 5", -- Missing translation
	EL_BOSS5_TARGET_FRAME_POWER_BAR_ALT = "Raid Boss Power Bar 5", -- Missing translation
	EL_CALENDAR_FRAME = "Calendar", -- Missing translation
	EL_CALENDAR_VIEW_EVENT_FRAME = "Calendar Event", -- Missing translation
	EL_CASTING_BAR_FRAME = "Casting Bar", -- Missing translation
	EL_CHALLENGES_KEYSTONE_FRAME = "Challenge Keystone", -- Missing translation
	EL_CHANNEL_PULLOUT = "Channel Pullout", -- Missing translation
	EL_CHARACTER_BAG0_SLOT = "Bag Button 1", -- Missing translation
	EL_CHARACTER_BAG1_SLOT = "Bag Button 2", -- Missing translation
	EL_CHARACTER_BAG2_SLOT = "Bag Button 3", -- Missing translation
	EL_CHARACTER_BAG3_SLOT = "Bag Button 4", -- Missing translation
	EL_CHARACTER_FRAME = "Character / Reputation / Currency", -- Missing translation
	EL_CHAT_CONFIG_FRAME = "Chat Channel Configuration", -- Missing translation
	EL_CHAT_EDIT_BOXES_LENGTH_MOVER = "Chat Edit Box Length", -- Missing translation
	EL_CHAT_EDIT_BOXES_MOVER = "Chat Edit Box", -- Missing translation
	EL_CLASS_TRAINER_FRAME = "Class Trainer", -- Missing translation
	EL_COLLECTIONS_JOURNAL = "Collections", -- Missing translation
	EL_COLOR_PICKER_FRAME = "Color Picker", -- Missing translation
	EL_COMBO_FRAME = "Target Combo Points Display", -- Missing translation
	EL_COMBO_POINT_PLAYER_FRAME = "Combo Point Frame", -- Missing translation
	EL_COMMUNITIES_FRAME = "Communities", -- Missing translation
	EL_COMPACT_RAID_FRAME_BUFF_TOOLTIPS_MOVER = "Raid Frame Buff Tooltips", -- Missing translation
	EL_COMPACT_RAID_FRAME_DEBUFF_TOOLTIPS_MOVER = "Raid Frame Debuff Tooltips", -- Missing translation
	EL_COMPACT_RAID_FRAME_MANAGER = "Raid Manager", -- Missing translation
	EL_COMPACT_RAID_FRAME_MANAGER_TOGGLE_BUTTON = "Raid Manager Toggle Button", -- Missing translation
	EL_COMPACT_RAID_GROUP1 = "Raid Group 1", -- Missing translation
	EL_COMPACT_RAID_GROUP2 = "Raid Group 2", -- Missing translation
	EL_COMPACT_RAID_GROUP3 = "Raid Group 3", -- Missing translation
	EL_COMPACT_RAID_GROUP4 = "Raid Group 4", -- Missing translation
	EL_COMPACT_RAID_GROUP5 = "Raid Group 5", -- Missing translation
	EL_COMPACT_RAID_GROUP6 = "Raid Group 6", -- Missing translation
	EL_COMPACT_RAID_GROUP7 = "Raid Group 7", -- Missing translation
	EL_COMPACT_RAID_GROUP8 = "Raid Group 8", -- Missing translation
	EL_CONSOLIDATED_BUFFS = "Consolidated Buffs", -- Missing translation
	EL_CONSOLIDATED_BUFFS_TOOLTIP = "Player Buffs - Consolidated Buffs Tooltip", -- Missing translation
	EL_CRITERIA_ALERT_FRAME1 = "Criteria Alert 1", -- Missing translation
	EL_CRITERIA_ALERT_FRAME2 = "Criteria Alert 2", -- Missing translation
	EL_DIGSITE_COMPLETE_TOAST_FRAME = "Digsite Complete Toast Frame", -- Missing translation
	EL_DRESS_UP_FRAME = "Dressing Room", -- Missing translation
	EL_DUNGEON_COMPLETION_ALERT_FRAME1 = "Dungeon Completion Alert", -- Missing translation
	EL_DURABILITY_FRAME = "Durability Figure", -- Missing translation
	EL_ENCOUNTER_JOURNAL = "Dungeon Journal", -- Missing translation
	EL_EXTRA_ABILITY_CONTAINER = "Extra Ability Bar", -- Missing translation
	EL_FLIGHT_MAP_FRAME = "Flight Map", -- Missing translation
	EL_FLOATING_BATTLE_PET_TOOLTIP = "FloatingBattlePetTooltip", -- Missing translation
	EL_FLOATING_PET_BATTLE_ABILITY_TOOLTIP = "FloatingPetBattleAbilityTooltip", -- Missing translation
	EL_FOCUS_BUFFS_MOVER = "Focus Buffs", -- Missing translation
	EL_FOCUS_DEBUFFS_MOVER = "Focus Debuffs", -- Missing translation
	EL_FOCUS_FRAME = "Focus", -- Missing translation
	EL_FOCUS_FRAME_SPELL_BAR = "Focus Casting Bar", -- Missing translation
	EL_FOCUS_FRAME_TEXTURE_FRAME_PVP_ICON = "Focus PVP Icon", -- Missing translation
	EL_FOCUS_FRAME_TOT = "Target of Focus", -- Missing translation
	EL_FOCUS_FRAME_TOT_DEBUFFS_MOVER = "Target of Focus Debuffs", -- Missing translation
	EL_FRAMERATE_LABEL_MOVER = "Framerate", -- Missing translation
	EL_FRIENDS_FRAME = "Social - Friends / Who / Guild / Chat / Raid", -- Missing translation
	EL_GAME_MENU_BUTTON_MOVE_ANYTHING = "MoveAnything Game Menu Button", -- Missing translation
	EL_GAME_MENU_FRAME = "Game Menu", -- Missing translation
	EL_GAME_TIME_FRAME = "Minimap Calendar Button", -- Missing translation
	EL_GARRISON_BUILDING_ALERT_FRAME = "Garrison Building Alert", -- Missing translation
	EL_GARRISON_BUILDING_FRAME = "Garrison Architect", -- Missing translation
	EL_GARRISON_CAPACITIVE_DISPLAY_FRAME = "Garrison Work Order", -- Missing translation
	EL_GARRISON_CAPACITIVE_DISPLAY_FRAME = "Work Order", -- Missing translation
	EL_GARRISON_FOLLOWER_ALERT_FRAME = "Garrison Follower Alert", -- Missing translation
	EL_GARRISON_LANDING_PAGE = "Garrison Report", -- Missing translation
	EL_GARRISON_LANDING_PAGE_MINIMAP_BUTTON = "Garrison Minimap Button", -- Missing translation
	EL_GARRISON_MISSION_ALERT_FRAME = "Garrison Mission Alert", -- Missing translation
	EL_GARRISON_MISSION_FRAME = "Garrison Missions", -- Missing translation
	EL_GARRISON_MONUMENT_FRAME = "Garrison Monuments", -- Missing translation
	EL_GARRISON_SHIP_FOLLOWER_ALERT_FRAME = "Shipyard Follower Alert", -- Missing translation
	EL_GARRISON_SHIP_MISSION_ALERT_FRAME = "Shipyard Mission Alert", -- Missing translation
	EL_GARRISON_SHIPYARD_FRAME = "Naval Operations", -- Missing translation
	EL_GARRISON_TALENT_ALERT_FRAME = "Order Hall Talent Alert", -- Missing translation
	EL_GHOST_FRAME = "Return to Graveyard Button", -- Missing translation
	EL_GOSSIP_FRAME = "Gossip", -- Missing translation
	EL_GROUP_LOOT_CONTAINER = "All Loot Roll Frame", -- Missing translation
	EL_GROUP_LOOT_FRAME1 = "Loot Roll 1", -- Missing translation
	EL_GROUP_LOOT_FRAME2 = "Loot Roll 2", -- Missing translation
	EL_GROUP_LOOT_FRAME3 = "Loot Roll 3", -- Missing translation
	EL_GROUP_LOOT_FRAME4 = "Loot Roll 4", -- Missing translation
	EL_GUILD_BANK_FRAME = "Guild Bank", -- Missing translation
	EL_GUILD_BANK_FRAME_DEPOSIT_BUTTON = "Guild Bank Deposit Button", -- Missing translation
	EL_GUILD_BANK_FRAME_WITHDRAW_BUTTON = "Guild Bank Withdraw Button", -- Missing translation
	EL_GUILD_BANK_INFO_SAVE_BUTTON = "Guild Bank Save Button", -- Missing translation
	EL_GUILD_BANK_ITEM_TOOLTIP_MOVER = "Tooltip - Guild Bank Item", -- Missing translation
	EL_GUILD_BANK_MONEY_FRAME = "Guild Bank Money", -- Missing translation
	EL_GUILD_BANK_MONEY_FRAME_COPPER_BUTTON = "Guild Bank Money Copper", -- Missing translation
	EL_GUILD_BANK_MONEY_FRAME_GOLD_BUTTON = "Guild Bank Money Gold", -- Missing translation
	EL_GUILD_BANK_MONEY_FRAME_SILVER_BUTTON = "Guild Bank Money Silver", -- Missing translation
	EL_GUILD_BANK_TAB1 = "Guild Bank Tab 1", -- Missing translation
	EL_GUILD_BANK_TAB2 = "Guild Bank Tab 2", -- Missing translation
	EL_GUILD_BANK_TAB3 = "Guild Bank Tab 3", -- Missing translation
	EL_GUILD_BANK_TAB4 = "Guild Bank Tab 4", -- Missing translation
	EL_GUILD_BANK_TAB5 = "Guild Bank Tab 5", -- Missing translation
	EL_GUILD_BANK_TAB6 = "Guild Bank Tab 6", -- Missing translation
	EL_GUILD_BANK_TAB7 = "Guild Bank Tab 7", -- Missing translation
	EL_GUILD_BANK_TAB8 = "Guild Bank Tab 8", -- Missing translation
	EL_GUILD_BANK_WITHDRAW_MONEY_FRAME = "Guild Bank Withdraw Money", -- Missing translation
	EL_GUILD_BANK_WITHDRAW_MONEY_FRAME_COPPER_BUTTON = "Guild Bank Withdraw Money Copper", -- Missing translation
	EL_GUILD_BANK_WITHDRAW_MONEY_FRAME_GOLD_BUTTON = "Guild Bank Withdraw Money Gold", -- Missing translation
	EL_GUILD_BANK_WITHDRAW_MONEY_FRAME_SILVER_BUTTON = "Guild Bank Withdraw Money Silver", -- Missing translation
	EL_GUILD_CHALLENGE_ALERT_FRAME = "Guild Challenge Achievement Alert", -- Missing translation
	EL_GUILD_CONTROL_UI = "Guild Control", -- Missing translation
	EL_GUILD_FRAME = "Guild", -- Missing translation
	EL_GUILD_INFO_FRAME = "Guild Info", -- Missing translation
	EL_GUILD_INSTANCE_DIFFICULTY = "Minimap Guild Group Flag", -- Missing translation
	EL_GUILD_INVITE_FRAME = "Guild Invite", -- Missing translation
	EL_GUILD_ITEM_SEARCH_BOX = "Guild Bank Item Seach", -- Missing translation
	EL_GUILD_LOG_CONTAINER = "Guild Log", -- Missing translation
	EL_GUILD_MEMBER_DETAIL_FRAME = "Guild Member Details", -- Missing translation
	EL_GUILD_REGISTRAR_FRAME = "Guild Registrar", -- Missing translation
	EL_HELP_FRAME = "GM Help", -- Missing translation
	EL_HELP_OPEN_TICKET_BUTTON_TUTORIAL = "Ticket Status Tutorial", -- Missing translation
	EL_HELP_OPEN_WEB_TICKET_BUTTON = "Ticket Status", -- Missing translation
	EL_HONOR_WATCH_BAR = "Honor Bar", -- Missing translation
	EL_INSPECT_FRAME = "Inspect", -- Missing translation
	EL_INTERFACE_OPTIONS_FRAME = "Interface Options", -- Missing translation
	EL_ITEM_REF_TOOLTIP = "Chat Popup Tooltip", -- Missing translation
	EL_ITEM_SOCKETING_FRAME = "Gem Socketing", -- Missing translation
	EL_ITEM_TEXT_FRAME = "Reading Materials", -- Missing translation
	EL_ITEM_UPGRADE_FRAME = "Item Upgrade", -- Missing translation
	EL_KEY_BINDING_FRAME = "Keybinding Options", -- Missing translation
	EL_KEY_RING_BUTTON = "Key Ring Button", -- Missing translation
	EL_KEY_RING_FRAME = "Key Ring", -- Missing translation
	EL_LEVEL_UP_DISPLAY = "Level Up Display", -- Missing translation
	EL_LEVEL_UP_DISPLAY = "LevelUpDisplay", -- Missing translation
	EL_LFD_PARENT_FRAME = "Dungeon Finder", -- Missing translation
	EL_LFD_ROLE_CHECK_POPUP = "Dungeon Role Check Popup", -- Missing translation
	EL_LFG_DUNGEON_READY_DIALOG = "Dungeon Ready Dialog", -- Missing translation
	EL_LFG_DUNGEON_READY_POPUP = "Dungeon Ready Popup", -- Missing translation
	EL_LFG_DUNGEON_READY_STATUS = "Dungeon Ready Status", -- Missing translation
	EL_LFG_SEARCH_STATUS = "Dungeon/Raid Finder Queue Status", -- Missing translation
	EL_LFR_PARENT_FRAME = "Looking For Raid", -- Missing translation
	EL_LOOKING_FOR_GUILD_FRAME = "Guild Finder", -- Missing translation
	EL_LOOT_FRAME = "Loot", -- Missing translation
	EL_LOOT_WON_ALERT_FRAME1 = "Loot Won Alert Frame 1", -- Missing translation
	EL_LOOT_WON_ALERT_MOVER1 = "Loot Won Alert Frame1", -- Missing translation
	EL_LOOT_WON_ALERT_MOVER10 = "Loot Won Alert Frame10", -- Missing translation
	EL_LOOT_WON_ALERT_MOVER2 = "Loot Won Alert Frame2", -- Missing translation
	EL_LOOT_WON_ALERT_MOVER3 = "Loot Won Alert Frame3", -- Missing translation
	EL_LOOT_WON_ALERT_MOVER4 = "Loot Won Alert Frame4", -- Missing translation
	EL_LOOT_WON_ALERT_MOVER5 = "Loot Won Alert Frame5", -- Missing translation
	EL_LOOT_WON_ALERT_MOVER6 = "Loot Won Alert Frame6", -- Missing translation
	EL_LOOT_WON_ALERT_MOVER7 = "Loot Won Alert Frame7", -- Missing translation
	EL_LOOT_WON_ALERT_MOVER8 = "Loot Won Alert Frame8", -- Missing translation
	EL_LOOT_WON_ALERT_MOVER9 = "Loot Won Alert Frame9", -- Missing translation
	EL_LOSS_OF_CONTROL_FRAME = "Loss Of Control", -- Missing translation
	EL_MA_FE_MOVER = "MoveAnything Frame Editor Config", -- Missing translation
	EL_MA_NUDGER = "MoveAnything Nudger", -- Missing translation
	EL_MA_OPTIONS = "MoveAnything Window", -- Missing translation
	EL_MACRO_FRAME = "Macro Options", -- Missing translation
	EL_MACRO_FRAME = "Macros", -- Missing translation
	EL_MACRO_POPUP_FRAME = "Macro Name & Icon", -- Missing translation
	EL_MAGE_ARCANE_CHARGES_FRAME = "Mage Arcane Charges Power Frame", -- Missing translation
	EL_MAIL_FRAME = "Mailbox", -- Missing translation
	EL_MAIN_MENU_BAR = "Main Bar", -- Missing translation
	EL_MAIN_MENU_BAR_ART_FRAME_LEFT_END_CAP_MOVER = "Left Gryphon", -- Missing translation
	EL_MAIN_MENU_BAR_ART_FRAME_RIGHT_END_CAP_MOVER = "Right Gryphon", -- Missing translation
	EL_MAIN_MENU_BAR_BACKPACK_BUTTON = "Backpack Button", -- Missing translation
	EL_MAIN_MENU_BAR_MAX_LEVEL_BAR = "Max Level Bar Filler", -- Missing translation
	EL_MAIN_MENU_BAR_PAGE_NUMBER = "Action Bar Page Number", -- Missing translation
	EL_MAIN_MENU_BAR_PAGE_NUMBER_MOVER = "Action Bar Page Number", -- Missing translation
	EL_MAIN_MENU_BAR_VEHICLE_LEAVE_BUTTON = "Leave Vehicle Button", -- Missing translation
	EL_MAIN_MENU_EXP_BAR = "Experience Bar", -- Missing translation
	EL_MERCHANT_FRAME = "Merchant", -- Missing translation
	EL_MICRO_BUTTON_AND_BAGS_BAR = "Micro Bags Bar", -- Missing translation
	EL_MICRO_BUTTONS_MOVER = "Micro Menu", -- Missing translation
	EL_MICRO_BUTTONS_SPLIT_MOVER = "Micro Menu - Split", -- Missing translation
	EL_MICRO_BUTTONS_VEHICLE_MOVER = "Vehicle Micro Bar", -- Missing translation
	EL_MICRO_BUTTONS_VERTICAL_MOVER = "Micro Menu - Vertical", -- Missing translation
	EL_MINI_MAP_BATTLEFIELD_FRAME = "Battleground Minimap Button", -- Missing translation
	EL_MINI_MAP_INSTANCE_DIFFICULTY = "Minimap Dungeon Difficulty", -- Missing translation
	EL_MINI_MAP_MAIL_FRAME = "Minimap Mail Notification", -- Missing translation
	EL_MINI_MAP_TRACKING = "Minimap Tracking Button", -- Missing translation
	EL_MINI_MAP_WORLD_MAP_BUTTON = "Minimap World Map Button", -- Missing translation
	EL_MINIMAP_BACKDROP = "Minimap Round Border", -- Missing translation
	EL_MINIMAP_BORDER = "Minimap Border Texture", -- Missing translation
	EL_MINIMAP_BORDER_TOP = "Minimap Top Border", -- Missing translation
	EL_MINIMAP_CLUSTER = "Minimap", -- Missing translation
	EL_MINIMAP_NORTH_TAG = "Minimap North Indicator", -- Missing translation
	EL_MINIMAP_ZONE_TEXT_BUTTON = "Minimap Zone Text", -- Missing translation
	EL_MINIMAP_ZOOM_IN = "Minimap Zoom In Button", -- Missing translation
	EL_MINIMAP_ZOOM_OUT = "Minimap Zoom Out Button", -- Missing translation
	EL_MIRROR_TIMER1 = "BreathFatigue Bar", -- Missing translation
	EL_MISSING_LOOT_FRAME = "Missing Loot Frame", -- Missing translation
	EL_MODEL_PREVIEW_FRAME = "Store Model Preview", -- Missing translation
	EL_MONEY_WON_ALERT_MOVER1 = "Money Won Frame1", -- Missing translation
	EL_MONEY_WON_ALERT_MOVER2 = "Money Won Frame2", -- Missing translation
	EL_MONEY_WON_ALERT_MOVER3 = "Money Won Frame3", -- Missing translation
	EL_MONEY_WON_ALERT_MOVER4 = "Money Won Frame4", -- Missing translation
	EL_MONEY_WON_ALERT_MOVER5 = "Money Won Frame5", -- Missing translation
	EL_MONK_HARMONY_BAR_FRAME_MOVER = "Monk Chi Frame", -- Missing translation
	EL_MONK_STAGGER_BAR = "Monk Stagger Frame", -- Missing translation
	EL_MULTI_BAR_BOTTOM_LEFT = "Bottom Left Action Bar", -- Missing translation
	EL_MULTI_BAR_BOTTOM_RIGHT = "Bottom Right Action Bar", -- Missing translation
	EL_MULTI_BAR_LEFT = "Right Action Bar 2", -- Missing translation
	EL_MULTI_BAR_LEFT_HORIZONTAL_MOVER = "Right Action Bar 2 - Horizontal", -- Missing translation
	EL_MULTI_BAR_LEFT_MOVER = "Right Action Bar 2", -- Missing translation
	EL_MULTI_BAR_RIGHT_HORIZONTAL_MOVER = "Right Action Bar - Horizontal", -- Missing translation
	EL_MULTI_BAR_RIGHT_MOVER = "Right Action Bar", -- Missing translation
	EL_MULTI_BAR_RIGHT_MOVERT = "Right Action Bar", -- Missing translation
	EL_MULTI_CAST_ACTION_BAR_FRAME = "Shaman Totem Frame", -- Missing translation
	EL_OBJECTIVE_TRACKER_BONUS_BANNER_FRAME = "Objectives Banner Frame", -- Missing translation
	EL_OBJECTIVE_TRACKER_FRAME_MOVER = "Objectives Window", -- Missing translation
	EL_OBJECTIVE_TRACKER_FRAME_SCALE_MOVER = "Objectives Window Scale", -- Missing translation
	EL_OPEN_MAIL_FRAME = "Open Mail", -- Missing translation
	EL_ORDER_HALL_COMMAND_BAR = "Order Hall Command Bar", -- Missing translation
	EL_ORDER_HALL_MISSION_FRAME = "Order Hall Missions", -- Missing translation
	EL_ORDER_HALL_TALENT_FRAME = "Order Hall Talents", -- Missing translation
	EL_OVERRIDE_ACTION_BAR = "Vehicle Bar", -- Missing translation
	EL_OVERRIDE_ACTION_BAR_EXP_BAR = "Vehicle Experience Bar", -- Missing translation
	EL_OVERRIDE_ACTION_BAR_HEALTH_BAR = "Vehicle Health Bar", -- Missing translation
	EL_OVERRIDE_ACTION_BAR_LEAVE_FRAME = "Vehicle Leave Frame", -- Missing translation
	EL_OVERRIDE_ACTION_BAR_POWER_BAR = "Vehicle Power Bar", -- Missing translation
	EL_OVERRIDE_ACTION_BUTTONS_MOVER = "Vehicle Action Bar", -- Missing translation
	EL_PALADIN_POWER_BAR_FRAME = "Paladin Power Frame", -- Missing translation
	EL_PARTY_MEMBER_FRAME1 = "Party Member 1", -- Missing translation
	EL_PARTY_MEMBER_FRAME1_PET_FRAME = "Party Pet 1", -- Missing translation
	EL_PARTY_MEMBER_FRAME2 = "Party Member 2", -- Missing translation
	EL_PARTY_MEMBER_FRAME2_PET_FRAME = "Party Pet 2", -- Missing translation
	EL_PARTY_MEMBER_FRAME3 = "Party Member 3", -- Missing translation
	EL_PARTY_MEMBER_FRAME3_PET_FRAME = "Party Pet 3", -- Missing translation
	EL_PARTY_MEMBER_FRAME4 = "Party Member 4", -- Missing translation
	EL_PARTY_MEMBER_FRAME4_PET_FRAME = "Party Pet 4", -- Missing translation
	EL_PARTY_MEMBER1_DEBUFFS_MOVER = "Party Member 1 Debuffs", -- Missing translation
	EL_PARTY_MEMBER2_DEBUFFS_MOVER = "Party Member 2 Debuffs", -- Missing translation
	EL_PARTY_MEMBER3_DEBUFFS_MOVER = "Party Member 3 Debuffs", -- Missing translation
	EL_PARTY_MEMBER4_DEBUFFS_MOVER = "Party Member 4 Debuffs", -- Missing translation
	EL_PET_ACTION_BUTTONS_MOVER = "Pet Action Bar", -- Missing translation
	EL_PET_ACTION_BUTTONS_VERTICAL_MOVER = "Pet Action Bar - Vertical", -- Missing translation
	EL_PET_BATTLE_MOVER1 = "Player Pet Frame", -- Missing translation
	EL_PET_BATTLE_MOVER11 = "Ally Pet 2", -- Missing translation
	EL_PET_BATTLE_MOVER12 = "Ally Pet 3", -- Missing translation
	EL_PET_BATTLE_MOVER2 = "Enemy Pet Frame", -- Missing translation
	EL_PET_BATTLE_MOVER22 = "Enemy Pet 2", -- Missing translation
	EL_PET_BATTLE_MOVER23 = "Enemy Pet 3", -- Missing translation
	EL_PET_BATTLE_MOVER24 = "Ally Pet Buffs", -- Missing translation
	EL_PET_BATTLE_MOVER25 = "Ally Pet Debuffs", -- Missing translation
	EL_PET_BATTLE_MOVER26 = "Ally Pet Pad Buffs", -- Missing translation
	EL_PET_BATTLE_MOVER27 = "Ally Pet Pad Debuffs", -- Missing translation
	EL_PET_BATTLE_MOVER28 = "Enemy Pet Buffs", -- Missing translation
	EL_PET_BATTLE_MOVER29 = "Enemy Pet Debuffs", -- Missing translation
	EL_PET_BATTLE_MOVER3 = "Weather", -- Missing translation
	EL_PET_BATTLE_MOVER30 = "Enemy Pet Pad Buffs", -- Missing translation
	EL_PET_BATTLE_MOVER31 = "Enemy Pet Pad Debuffs", -- Missing translation
	EL_PET_BATTLE_MOVER4 = "Pass Button", -- Missing translation
	EL_PET_BATTLE_MOVER5 = "Pet Selection Frame", -- Missing translation
	EL_PET_BATTLE_MOVER6 = "Bottom Frame", -- Missing translation
	EL_PET_BATTLE_MOVER7 = "Top Right Art", -- Missing translation
	EL_PET_BATTLE_MOVER8 = "Top Left Art", -- Missing translation
	EL_PET_BATTLE_MOVER9 = "Top Left Center", -- Missing translation
	EL_PET_BATTLE_PRIMARY_ABILITY_TOOLTIP = "PetBattle Primary Ability Tooltip", -- Missing translation
	EL_PET_BATTLE_PRIMARY_UNIT_TOOLTIP = "PetBattle Primary Unit Tooltip", -- Missing translation
	EL_PET_CASTING_BAR_FRAME = "Pet Casting Bar", -- Missing translation
	EL_PET_DEBUFFS_MOVER = "Pet Debuffs", -- Missing translation
	EL_PET_FRAME = "Pet", -- Missing translation
	EL_PET_STABLE_FRAME = "Pet Stable", -- Missing translation
	EL_PLAYER_ATTACK_BACKGROUND = "Player Attack Icon's Background", -- Missing translation
	EL_PLAYER_ATTACK_GLOW = "Player Attack Icon's Glow", -- Missing translation
	EL_PLAYER_ATTACK_ICON = "Player Attack Icon", -- Missing translation
	EL_PLAYER_BUFFS_MOVER = "Player Buffs Default", -- Missing translation
	EL_PLAYER_BUFFS_MOVER2 = "Player Buffs From Right to Left", -- Missing translation
	EL_PLAYER_DEBUFFS_MOVER = "Player Debuffs Default", -- Missing translation
	EL_PLAYER_DEBUFFS_MOVER2 = "Player Debuffs From Right to Left", -- Missing translation
	EL_PLAYER_FRAME = "Player", -- Missing translation
	EL_PLAYER_FRAME_ALTERNATE_MANA_BAR = "Alternate Mana Bar", -- Missing translation
	EL_PLAYER_FRAME_GROUP_INDICATOR = "Player Group Indicator", -- Missing translation
	EL_PLAYER_HIT_INDICATOR = "Heal/Damage Numbers", -- Missing translation
	EL_PLAYER_LEADER_ICON = "Player Leader Icon", -- Missing translation
	EL_PLAYER_MASTER_ICON = "Player Master Icon", -- Missing translation
	EL_PLAYER_POWER_BAR_ALT_MOVER = "Player Alternative Power Bar", -- Missing translation
	EL_PLAYER_PVP_ICON = "Player PVP Icon", -- Missing translation
	EL_PLAYER_REST_GLOW = "Player Rest Icon's Glow", -- Missing translation
	EL_PLAYER_REST_ICON = "Player Rest Icon", -- Missing translation
	EL_PLAYER_STATUS_GLOW = "Player Status Glow", -- Missing translation
	EL_PLAYER_STATUS_TEXTURE = "Player Status Texture", -- Missing translation
	EL_PLAYER_TALENT_FRAME = "Specialization / Talents / Glyphs", -- Missing translation
	EL_PLAYER_TALENT_FRAME = "Talents / Glyphs", -- Missing translation
	EL_PRESTIGE_LEVEL_UP_BANNER = "Prestige Banner", -- Missing translation
	EL_PVE_FRAME = "Dungeon Finder", -- Missing translation
	EL_PVP_BANNER_FRAME = "Arena Banner", -- Missing translation
	EL_PVP_READY_DIALOG = "PVP Ready Dialog", -- Missing translation
	EL_PVP_READY_POPUP = "PVP Ready Popup", -- Missing translation
	EL_PVP_TEAM_DETAILS = "Arena Team Details", -- Missing translation
	EL_PVPUI_FRAME = "PVP Window", -- Missing translation
	EL_QUEST_CHOICE_FRAME = "Quest Choice Frame", -- Missing translation
	EL_QUEST_FRAME = "Quest Offer / Return", -- Missing translation
	EL_QUEST_LOG_DETAIL_FRAME = "Quest Details", -- Missing translation
	EL_QUEST_LOG_POPUP_DETAIL_FRAME = "Quest Details", -- Missing translation
	EL_QUEST_NPC_MODEL = "Quest Log NPC Model", -- Missing translation
	EL_QUEST_TIMER_FRAME = "Quest Timer", -- Missing translation
	EL_QUEUE_STATUS_FRAME = "Battleground Minimap Button Tooltip", -- Missing translation
	EL_QUEUE_STATUS_FRAME = "Dungeon Status Button Tooltip", -- Missing translation
	EL_QUEUE_STATUS_MINIMAP_BUTTON = "Battleground Minimap Button", -- Missing translation
	EL_QUEUE_STATUS_MINIMAP_BUTTON = "Dungeon Status Button", -- Missing translation
	EL_QUEUE_STATUS_MINIMAP_BUTTON = "Minimap Queue Status Button", -- Missing translation
	EL_QUICK_JOIN_TOAST_BUTTON = "Quick Join Toast Button", -- Missing translation
	EL_QUICK_JOIN_TOAST_MOVER = "Quick Join Toast", -- Missing translation
	EL_QUICK_JOIN_TOAST2_MOVER = "Quick Join Toast 2", -- Missing translation
	EL_RAID_BOSS_EMOTE_FRAME = "Raid Boss Emote Display", -- Missing translation
	EL_RAID_BROWSER_FRAME = "Other Raids", -- Missing translation
	EL_RAID_PARENT_FRAME = "Raid Finder", -- Missing translation
	EL_RAID_UNIT_FRAMES_MOVER = "Raid Unit Frames", -- Missing translation
	EL_RAID_WARNING_FRAME = "Raid Warnings", -- Missing translation
	EL_READY_CHECK_FRAME = "Ready Check", -- Missing translation
	EL_REFORGING_FRAME = "Reforge", -- Missing translation
	EL_REPORT_CHEATING_DIALOG = "Report Player Cheating", -- Missing translation
	EL_REPORT_PLAYER_NAME_DIALOG = "Report Player Name", -- Missing translation
	EL_REPUTATION_DETAIL_FRAME = "Reputation Details", -- Missing translation
	EL_REPUTATION_WATCH_BAR = "Reputation Tracker Bar", -- Missing translation
	EL_ROLE_POLL_POPUP = "Raid Role Popup", -- Missing translation
	EL_RUNE_FRAME = "Deathknight Rune Frame", -- Missing translation
	EL_SCENARIO_ALERT_FRAME1 = "Scenario Completion Alert 1", -- Missing translation
	EL_SCENARIO_ALERT_FRAME2 = "Scenario Completion Alert 2", -- Missing translation
	EL_SIDE_DRESS_UP_FRAME = "Auction House Dressing Room", -- Missing translation
	EL_SPELL_ACTIVATION_OVERLAY_FRAME = "Class Ability Proc", -- Missing translation
	EL_SPELL_BOOK_FRAME = "Spellbook / Professions", -- Missing translation
	EL_STANCE_BUTTONS_MOVER = "Stance Buttons", -- Missing translation
	EL_STANCE_BUTTONS_VERTICAL_MOVER = "Stance Buttons - Vertical", -- Missing translation
	EL_START_SPLASH = "StartSplash", -- Missing translation
	EL_STATIC_POPUP1 = "Static Popup 1", -- Missing translation
	EL_STATIC_POPUP2 = "Static Popup 2", -- Missing translation
	EL_STATIC_POPUP3 = "Static Popup 3", -- Missing translation
	EL_STATIC_POPUP4 = "Static Popup 4", -- Missing translation
	EL_STORE_PURCHASE_ALERT_FRAME = "Store Purchase Alert", -- Missing translation
	EL_STREAMING_ICON = "Streaming Download Icon", -- Missing translation
	EL_SUB_ZONE_TEXT_FRAME = "Zoning Subzone Text", -- Missing translation
	EL_TABARD_FRAME = "Tabard Design", -- Missing translation
	EL_TALENT_MICRO_BUTTON_ALERT = "Unsaved Talent Changes Alert", -- Missing translation
	EL_TALKING_HEAD_FRAME = "Quest Talking Head Frame", -- Missing translation
	EL_TARGET_BUFFS_MOVER = "Target Buffs", -- Missing translation
	EL_TARGET_DEBUFFS_MOVER = "Target Debuffs", -- Missing translation
	EL_TARGET_FRAME = "Target", -- Missing translation
	EL_TARGET_FRAME_NUMERICAL_THREAT = "Target Threat Indicator", -- Missing translation
	EL_TARGET_FRAME_POWER_BAR_ALT_MOVER = "Target Alternative Power Bar", -- Missing translation
	EL_TARGET_FRAME_SPELL_BAR = "Target Casting Bar", -- Missing translation
	EL_TARGET_FRAME_TEXTURE_FRAME_PVP_ICON = "Target PVP Icon", -- Missing translation
	EL_TARGET_FRAME_TOT = "Target of Target", -- Missing translation
	EL_TARGET_FRAME_TOT_DEBUFFS_MOVER = "Target of Target Debuffs", -- Missing translation
	EL_TAXI_FRAME = "Flight Paths", -- Missing translation
	EL_TIME_ALERT_FRAME = "Time Alert Popup Message", -- Missing translation
	EL_TIME_MANAGER_CLOCK_BUTTON = "Minimap Clock Button", -- Missing translation
	EL_TIME_MANAGER_FRAME = "Alarm Clock", -- Missing translation
	EL_TIMER_TRACKER_TIMER1 = "Timer tracker", -- Missing translation
	EL_TOKEN_FRAME_POPUP = "Currency Options", -- Missing translation
	EL_TOOLTIP_MOVER = "Tooltip", -- Missing translation
	EL_TOTEM_FRAME = "Totem Frame", -- Missing translation
	EL_TRADE_FRAME = "Trade", -- Missing translation
	EL_TRADE_SKILL_FRAME = "Trade Skills", -- Missing translation
	EL_TUTORIAL_FRAME_ALERT_BUTTON = "Tutorials Alert Button", -- Missing translation
	EL_UI_ERRORS_FRAME = "Errors & Warning Display", -- Missing translation
	EL_UI_PANEL_MOVER1 = "Generic Info Panel 1 Left", -- Missing translation
	EL_UI_PANEL_MOVER2 = "Generic Info Panel 2 Center", -- Missing translation
	EL_UI_PANEL_MOVER3 = "Generic Info Panel 3 Right", -- Missing translation
	EL_UI_WIDGET_BELOW_MINIMAP_CONTAINER_FRAME = "Flag Capture Timer Bar", -- Missing translation
	EL_UI_WIDGET_POWER_BAR_CONTAINER_FRAME = "Power Ability Bar", -- Missing translation
	EL_UI_WIDGET_TOP_CENTER_CONTAINER_FRAME = "Battleground Scoreboard", -- Missing translation
	EL_VEHICLE_SEAT_INDICATOR = "Vehicle Seat Indicator", -- Missing translation
	EL_VIDEO_OPTIONS_FRAME = "Video Options", -- Missing translation
	EL_VOICE_CHAT_TALKERS = "Voice Chat Talkers", -- Missing translation
	EL_VOID_STORAGE_FRAME = "Void Storage", -- Missing translation
	EL_WARDROBE_FRAME = "Transmogrification", -- Missing translation
	EL_WARLOCK_POWER_FRAME = "Warlock Power Frame", -- Missing translation
	EL_WORLD_MAP_FRAME = "World Map", -- Missing translation
	EL_WORLD_MAP_LEVEL_DROP_DOWN = "Map Level", -- Missing translation
	EL_WORLD_MAP_POSITIONING_GUIDE = "Map Coordinates", -- Missing translation
	EL_WORLD_MAP_SHOW_DROP_DOWN = "Map Options", -- Missing translation
	EL_WORLD_MAP_TRACK_QUEST = "Map Track Quest", -- Missing translation
	EL_WORLD_QUEST_COMPLETE_ALERT_FRAME = "World Quest Complete Alert", -- Missing translation
	EL_WORLD_STATE_ALWAYS_UP_FRAME = "Top Center Status Display", -- Missing translation
	EL_ZONE_TEXT_FRAME = "Zoning Zone Text", -- Missing translation
	ELEMENT_NOT_FOUND = "UI element not found",
	ELEMENT_NOT_FOUND_NAMED = "UI element not found: %s",
	ENABLED = "Enabled",
	ERROR_FRAME_FAILED = "An error occured while syncing %s. Resetting the frame and /reload'ing before modifying it again might solve the issue. You can disable this message in the options. If the problem persists please report the following to the author: %s %s %s",
	ERROR_MODULE_FAILED = "An error occured while adjusting %s for %s. You can disable this message in the options. If the problem persists please report the following to the author: %s %s %s %s",
	ERROR_NOT_A_TABLE = "\"%s\" is an unsupported type",
	EXPORT = "Export",
	FE_FORCED_LOCK_POSITION_CONFIRM = "Force position lock? Click again within 5 seconds to confirm",
	FE_FORCED_LOCK_POSITION_TOOLTIP = "Overwrites the element's SetPoint method,\nreplacing it with an empty stub\n\nMay cause taint if the element is protected\nand the stub gets called during combat\n\nRequires a reload or relog after unchecking to\nrestore the original SetPoint method",
	FE_GROUP_RESET_CONFIRM = "Reset Group %i? Click again within 5 seconds to confirm",
	FE_GROUPS_TOOLTIP = "Group %i",
	FE_UNREGISTER_ALL_EVENTS_CONFIRM = "Unregister all events? Click again within 5 seconds to confirm",
	FE_UNREGISTER_ALL_EVENTS_TOOLTIP = "Unregisters any events that the frame is listening to,\nrendering the frame inert\n\nRe-enabling unregistered events will require a reload\nor relog after unchecking this checkbox",
	FORCE_LOCK_POSITION = "Force lock position",
	FRAME = "Frame",
	FRAME_NO_FRAME_EDITOR = "Frame editors is disabled for %s",
	FRAME_ONLY_ONCE_OPENED = "Can only interact with %s once it has been shown",
	FRAME_ONLY_WHEN_BANK_IS_OPEN = "Can only interact with %s while the bank is open",
	FRAME_ONLY_WHEN_VOIDSTORAGE_IS_OPEN = "Can only interact %s is open",
	FRAME_PROTECTED_DURING_COMBAT = "Can't interact with %s during combat",
	FRAME_UNPOSITIONED = "%s is currently unpositioned and can't be moved till it is",
	FRAME_VISIBILITY_ONLY = "%s can only be hidden",
	GROUPS = "Groups",
	HEIGHT = "Height",
	HIDDEN = "Hidden",
	HIDE_LAYER = "Hide Layer",
	HIGHLIGHT = "Highlight",
	HOOKALLOWED = "Toggles if MoveAnything will hook CreateFrame.\n\nRequires reload to take effect.",
	HOOKALLOWEDNO = "Disable frame creation hook",
	IMPORT = "Import",
	LIST_HEADING_CATEGORY_AND_FRAMES = "Categories and Frames",
	LIST_HEADING_HIDE = "Hide",
	LIST_HEADING_MOVER = "Mover",
	LIST_HEADING_SEARCH_RESULTS = "Search results: %i",
	MA_OPT_ALWAYS_SHOW_NUDGER = "Show Nudger with main window",
	MA_OPT_ALWAYS_SHOW_NUDGER_TOOLTIP = "Enable to show the nudger with the main window\n\nBy default the Nudger is only shown when interacting with frames.",
	MA_OPT_CLOSE_GUI_ON_ESCAPE = "Escape key closes main window",
	MA_OPT_DISABLE_ERROR_MESSAGES = "Disable error messages",
	MA_OPT_DISABLE_ERROR_MESSAGES_TOOLTIP = "Toggles printing of error messages on/off.",
	MA_OPT_DONT_HOOK_CREATE_FRAME = "Disable frame creation hook",
	MA_OPT_DONT_HOOK_CREATE_FRAME_TOOLTIP = "Toggles if MoveAnything will hook CreateFrame.\n\nRequires reload to take effect.",
	MA_OPT_DONT_SEARCH_FRAME_NAMES = "Don't search frame names",
	MA_OPT_DONT_SEARCH_FRAME_NAMES_TOOLTIP = "Disables searching of actual frame names.",
	MA_OPT_DONT_SYNC_WHEN_LEAVING_COMBAT = "Disable sync when leaving combat",
	MA_OPT_DONT_SYNC_WHEN_LEAVING_COMBAT_TOOLTIP = "Toggles if MoveAnything will synchronize pending frames when leaving combat.\n\nDisabling this may result in protected frames requiring a manual sync when leaving combat.",
	MA_OPT_EXPORT_PROFILE = "Export Profile",
	MA_OPT_FRAME_LIST_ROWS = "List rows",
	MA_OPT_IMPORT_PROFILE = "Import Profile",
	MA_OPT_NO_BAGS = "Disable bag container hook",
	MA_OPT_NO_BAGS_TOOLTIP = "Toggles if MoveAnything will hook containers.\n\nThis should be checked if you use another addon to move your bags.",
	MA_OPT_NO_MMMW = "Disable Minimap mousewheel zoom",
	MA_OPT_NO_MMMW_TOOLTIP = "Toggles Minimap mousewheel zoom on/off.\n\nRequires reload to take effect.",
	MA_OPT_PLAY_SOUND = "Play sound",
	MA_OPT_PLAY_SOUND_TOOLTIP = "Toggles if MoveAnything should play a sound when opening and closing the main window.",
	MA_OPT_PROFILE = "Profile",
	MA_OPT_PROFILE_ADD_TOOLTIP = "Add new",
	MA_OPT_PROFILE_DELETE_TOOLTIP = "Delete",
	MA_OPT_PROFILE_EXPORT = "Export",
	MA_OPT_PROFILE_EXPORT_IMPORT_LABEL = "%s Profile",
	MA_OPT_PROFILE_FROM = "From",
	MA_OPT_PROFILE_IMPORT = "Import",
	MA_OPT_PROFILE_NO_PROFILES = "No profiles available",
	MA_OPT_PROFILE_PROFILE_NOT_MODIFIED = "No profile has modified this frame",
	MA_OPT_PROFILE_PROFILE_NOT_MODIFIED_PLURAL = "No profiles has modified this frame",
	MA_OPT_PROFILE_RENAME_TOOLTIP = "Rename",
	MA_OPT_PROFILE_SAVE_AS_TOOLTIP = "Save as",
	MA_OPT_PROFILE_TO = "To",
	MA_OPT_RESET_ALL = "Reset All",
	MA_OPT_RESET_ALL_TOOLTIP = "Reset all\n\nReset MoveAnything to default settings. Deletes all frame settings, as well as the custom frame list",
	MA_OPT_RESET_PROFILE_TOOLTIP = "Reset profile\n\nResets the profile, deleting all stored frame settings for this profile.",
	MA_OPT_ROWS_SLIDER = "# of rows",
	MA_OPT_SHOW_TOOLTIPS = "Show tooltips",
	MA_OPT_SHOW_TOOLTIPS_TOOLTIP = "Toggles display of tooltips on/off\n\nPressing Shift when mousing over elements will reverse tooltip display behavior.",
	MA_OPT_SQUARE_MM = "Enable square Minimap",
	MA_OPT_SQUARE_MM_TOOLTIP = "Toggles square MiniMap on/off.\n\nHide \"Round Border\" in the \"Minimap\" category to get rid of the overlaying border.",
	MA_OPT_TEXT_STRING = "Text String",
	MA_OPT_VERSION = "Version",
	MOUSEOVER = "Mouseover",
	MOVER = "Mover",
	NAME = "Name",
	NO_NAMED_FRAMES_FOUND = "No named elements found",
	NOMMWP = "Toggles Minimap mousewheel zoom on/off.\n\nRequires reload to take effect.",
	NOMMWPNO = "Disable Minimap mousewheel zoom",
	NUDGER1 = "Show Nudger with main window",
	OF = "of",
	ONLY_ONCE_CREATED = "%s can only be modified after it has been created",
	OPTBAGS1 = "Toggles if MoveAnything will hook containers.\n\nThis should be checked if you use another addon to move your bags.",
	OPTBAGSTOOLTIP = "Disable bag container hook",
	OPTIONTOOLTIP1 = "Enable to show the nudger with the main window\n\nBy default the Nudger is only shown when interacting with frames.",
	OPTIONTOOLTIP2 = "Toggles display of tooltips on/off\n\nPressing Shift when mousing over elements will reverse tooltip display behavior.",
	OVERLAY = "Overlay",
	PARENT = "Parent",
	PARENTS_PARENT = "Parent's Parent",
	PLAYSOUND = "Play sound",
	PLAYSOUNDS = "Toggles if MoveAnything should play a sound when opening and closing the main window.",
	POSITION = "Position",
	PROFILE_ADD_TEXT = "Enter new profile name",
	PROFILE_ALREADY_EXISTS = "Profile \"%s\" already exists",
	PROFILE_CANT_DELETE_CURRENT_IN_COMBAT = "Can't delete current profile during combat",
	PROFILE_CANT_DELETE_DEFAULT = "The default profile can't be deleted",
	PROFILE_CURRENT = "Current",
	PROFILE_DELETE_TEXT = "Delete profile \"%s\"?",
	PROFILE_DELETED = "Profile deleted: %s",
	PROFILE_EXPORTED = "\"%s\" exported to \"%s\"",
	PROFILE_IMPORTED = "\"%s\" has been imported into \"%s\"",
	PROFILE_RENAME_TEXT = "Enter new name for \"%s\"",
	PROFILE_RESET_CONFIRM = "Reset all frames in the current profile?",
	PROFILE_SAVE_AS_TEXT = "Enter new profile name",
	PROFILE_UNKNOWN = "Unknown profile: %s",
	PROFILES = "Profiles",
	PROFILES_CANT_SWITCH_DURING_COMBAT = "Profiles can't be switched during combat",
	RENAME ="Rename",
	RESET = "Reset",
	RESET = "Reset",
	RESET_ALL_CONFIRM = "MoveAnything: Reset MoveAnything to installation state?\n\nWarning: this will delete all frame settings and clear out the custom frame list.",
	RESET_FRAME_CONFIRM = "Reset %s? Press again within 5 seconds to confirm",
	RESETALL1 = "Reset all\n\nReset MoveAnything to default settings. Deletes all frame settings, as well as the custom frame list",
	RESETPROFILE1 = "Reset profile\n\nResets the profile, deleting all stored frame settings for this profile.",
	RESETTING_FRAME = "Resetting %s",
	REVERT = "Revert",
	SAFE = "Safe",
	SAVE = "Save",
	SAVEAS = "Save as",
	SCALE = "Scale",
	SCALE = "Scale",
	SEARCH_TEXT = "Search",
	SHOW = "Show",
	SHOWTOOLTIPS = "Show tooltips",
	SQUARMAP = "Toggles square MiniMap on/off.\n\nHide \"Round Border\" in the \"Minimap\" category to get rid of the overlaying border.",
	SQUARMAPNO = "Enable square Minimap",
	STRATA = "Strata",
	SYNC = "Sync",
	TO = "to",
	TOGGLE_CATEGORIES_BUTTON_TOOLTIP = "Toggle all categories",
	TOGGLE_FRAME_EDITORS_BUTTON_TOOLTIP = "Toggle visibility on frame editors",
	TOGGLE_FRAME_STACK_BUTTON_TOOLTIP = "Toggle Blizzard's framestack tooltip\n\n A very helpful tool for finding frame names for use with /move or /hide",
	TOGGLE_MODIFIED_FRAMES_ONLY_BUTTON_TOOLTIP = "Show only modified frames",
	TOGGLE_MOVERS_BUTTON_TOOLTIP = "Toggles all movers",
	UNREGISTER_ALL_EVENTS = "Unregister all events",
	UNSERIALIZE_FRAME_INVALID_FORMAT = "Invalid format",
	UNSERIALIZE_FRAME_NAME_DIFFERS = "Imported frame name differs from import target",
	UNSERIALIZE_PROFILE_COMPLETED = "Imported %i element(s) into profile \"%s\"",
	UNSERIALIZE_PROFILE_NO_NAME = "Unable to locate profile name",
	UNSUPPORTED_FRAME = "Unsupported frame: %s",
	UNSUPPORTED_TYPE = "Unsupported type: %s",
	WIDTH = "Width",
	X_OFFSET = "X offset",
	Y_OFFSET = "Y offset"
}

_G.MOVANY = MOVANY
