if GetLocale() ~= "esES" and GetLocale() ~= "esMX" then
	return
end

local MOVANY = {
	ABSOLUTE_VALUES = "Absolute values", -- Missing translation
	ADD = "Añade",
	ADDNEW = "Añadir nuevo",
	ALPHA = "Alpha", -- Missing translation
	ARTWORK = "Artwork", -- Missing translation
	ATTACH = "Attach", -- Missing translation
	BACKGROUND = "Background", -- Missing translation
	BINDING_NAME_EDIT_FRAME_EXACT = "Edit frame - Exact", -- Missing translation
	BINDING_NAME_EDIT_FRAME_SAFE = "Edit frame - Safe", -- Missing translation
	BINDING_NAME_HIDE_FRAME_EXACT = "Hide frame - Exact", -- Missing translation
	BINDING_NAME_HIDE_FRAME_SAFE = "Hide frame - Safe", -- Missing translation
	BINDING_NAME_MOVE_FRAME_EXACT = "Move frame - Exact", -- Missing translation
	BINDING_NAME_MOVE_FRAME_SAFE = "Move frame - Safe", -- Missing translation
	BINDING_NAME_RESET_FRAME_EXACT = "Reset frame - Exact", -- Missing translation
	BINDING_NAME_RESET_FRAME_SAFE = "Reset frame - Safe", -- Missing translation
	BINDING_NAME_SHOW_FRAME_INFO = "Show frame info", -- Missing translation
	BINDING_NAME_SYNCHRONIZE_ALL_ELEMENTS = "Synchronize all elements", -- Missing translation
	BINDING_NAME_TOGGLE_MA_WINDOW = "Toggle MA window", -- Missing translation
	BORDER = "Border", -- Missing translation
	CAN_BE_SCALED_LABEL = "W: %s H: %s", -- Missing translation
	CAT_ACHIEVEMENTS_QUESTS = "Achievements & Quests", -- Missing translation
	CAT_ARENA = "Arena", -- Missing translation
	CAT_BATTLEGROUNDS_PVP = "Battlegrounds & PvP", -- Missing translation
	CAT_BLIZZARD_ACTION_BARS = "Blizzard Action Bars", -- Missing translation
	CAT_BLIZZARD_BAGS = "Blizzard Bags", -- Missing translation
	CAT_BLIZZARD_BANK_AND_VOID_STORAGE = "Blizzard Bank and VoidStorage", -- Missing translation
	CAT_BLIZZARD_BOTTOM_BAR = "Blizzard Bottom Bar", -- Missing translation
	CAT_BOSS_SPECIFIC_FRAMES = "Boss Specific Frames", -- Missing translation
	CAT_CLASS_SPECIFIC = "Class Specific", -- Missing translation
	CAT_CUSTOM_FRAMES = "Custom Frames", -- Missing translation
	CAT_DUNGEONS_RAIDS = "Dungeons & Raids", -- Missing translation
	CAT_GAME_MENU = "Game Menu", -- Missing translation
	CAT_GARRISON = "Garrison", -- Missing translation
	CAT_GUILD = "Guild", -- Missing translation
	CAT_INFO_PANELS = "Info Panels", -- Missing translation
	CAT_LOOT = "Loot", -- Missing translation
	CAT_MA_INTERNAL_ELEMENTS = "MA Internal Elements", -- Missing translation
	CAT_MAP = "Map", -- Missing translation
	CAT_MINIMAP = "Minimap", -- Missing translation
	CAT_MISCELLANEOUS = "Miscellaneous", -- Missing translation
	CAT_MOVE_ANYTHING = "MoveAnything", -- Missing translation
	CAT_ORDER_HALL = "Order Hall", -- Missing translation
	CAT_PET_BATTLE = "PetBattle", -- Missing translation
	CAT_SHIPYARD = "Shipyard", -- Missing translation
	CAT_STORE = "Store", -- Missing translation
	CAT_UNIT_FOCUS = "Unit: Focus", -- Missing translation
	CAT_UNIT_PARTY = "Unit: Party", -- Missing translation
	CAT_UNIT_PET = "Unit: Pet", -- Missing translation
	CAT_UNIT_PLAYER = "Unit: Player", -- Missing translation
	CAT_UNIT_TARGET = "Unit: Target", -- Missing translation
	CAT_VEHICLE = "Vehicle", -- Missing translation
	CLAMP_TO_SCREEN = "Clamp to screen", -- Missing translation
	CLOSEGUIONESC = "Tecla Escape cierra la ventana principal",
	CMD_SYNTAX_DELETE = "Sintaxis: /movedelete NombredelPerfil",
	CMD_SYNTAX_EXPORT = "Sintaxis: /moveexport NombredelPErfil",
	CMD_SYNTAX_HIDE = "Sintaxis: /hide NombredelPerfil",
	CMD_SYNTAX_IMPORT = "Sintaxis:/moveimport NombredelPerfil",
	CMD_SYNTAX_MAFE = "Sintaxis: /mafe Nombredelcuadro",
	CMD_SYNTAX_UNMOVE = "Sintaxis: /unmove Nombredelcuadro",
	DELETE = "Borrar",
	DISABLED_DURING_COMBAT = "Deshabilitado durante el combate",
	DISERRORMES = "Cambia impresión de los mensajes de error on/off.",
	DISERRORMESNO = "Desactivar los mensajes de error",
	DONSEARCHFRAMENAME = "Desactiva la búsqueda de nombres de marcos actuales.",
	DONTSEARCH = "No buscar los nombres de marcos",
	DONTSYNCINCOMBAT = "Cambia si MoveAnything sincronizara los marcos pendientes al salir de combate.\n\nDeshabilitar esto puede resultar en marcos protegidos que requieran una sincronización manual al salir de combate.",
	DONTSYNCINCOMBATNO = "Desactivar sincronización al salir de combate",
	EL_ACHIEVEMENT_ALERT_1 = "Achievement Alert 1", -- Missing translation
	EL_ACHIEVEMENT_ALERT_2 = "Achievement Alert 2", -- Missing translation
	EL_ACHIEVEMENTS = "Achievements", -- Missing translation
	EL_ACTION_BAR = "Action Bar", -- Missing translation
	EL_ACTION_BAR_PAGE_DOWN = "Action Bar Page Down", -- Missing translation
	EL_ACTION_BAR_PAGE_NUMBER = "Action Bar Page Number", -- Missing translation
	EL_ACTION_BAR_PAGE_NUMBER = "Action Bar Page Number", -- Missing translation
	EL_ACTION_BAR_PAGE_UP = "Action Bar Page Up", -- Missing translation
	EL_ACTION_BAR_VERTICAL = "Action Bar - Vertical", -- Missing translation
	EL_ACTION_STAUS = "Action Staus", -- Missing translation
	EL_ALARM_CLOCK = "Alarm Clock", -- Missing translation
	EL_ALERTS_FRAMES = "Alerts Frames", -- Missing translation
	EL_ALL_BAGS = "All Bags", -- Missing translation
	EL_ALL_LOOT_ROLL_FRAME = "All Loot Roll Frame", -- Missing translation
	EL_ALLY_PET_2 = "Ally Pet 2", -- Missing translation
	EL_ALLY_PET_3 = "Ally Pet 3", -- Missing translation
	EL_ALLY_PET_BUFFS = "Ally Pet Buffs", -- Missing translation
	EL_ALLY_PET_DEBUFFS = "Ally Pet Debuffs", -- Missing translation
	EL_ALLY_PET_PAD_BUFFS = "Ally Pet Pad Buffs", -- Missing translation
	EL_ALLY_PET_PAD_DEBUFFS = "Ally Pet Pad Debuffs", -- Missing translation
	EL_ALTERNATE_MANA_BAR = "Alternate Mana Bar", -- Missing translation
	EL_ALWAYS_UP_FRAME_1 = "AlwaysUp Frame 1", -- Missing translation
	EL_ALWAYS_UP_FRAME_2 = "AlwaysUp Frame 2", -- Missing translation
	EL_ALWAYS_UP_FRAME_3 = "AlwaysUp Frame 3", -- Missing translation
	EL_ARCHAEOLOGY = "Archaeology", -- Missing translation
	EL_ARCHEOLOGY_DIGSITE_PROGRESS_BAR = "Archeology Digsite ProgressBar", -- Missing translation
	EL_ARENA_BANNER = "Arena Banner", -- Missing translation
	EL_ARENA_ENEMY_1 = "Arena Enemy 1", -- Missing translation
	EL_ARENA_ENEMY_2 = "Arena Enemy 2", -- Missing translation
	EL_ARENA_ENEMY_3 = "Arena Enemy 3", -- Missing translation
	EL_ARENA_ENEMY_4 = "Arena Enemy 4", -- Missing translation
	EL_ARENA_ENEMY_5 = "Arena Enemy 5", -- Missing translation
	EL_ARENA_ENEMY_CASTING_BAR_1 = "Arena Enemy Casting Bar 1", -- Missing translation
	EL_ARENA_ENEMY_CASTING_BAR_2 = "Arena Enemy Casting Bar 2", -- Missing translation
	EL_ARENA_ENEMY_CASTING_BAR_3 = "Arena Enemy Casting Bar 3", -- Missing translation
	EL_ARENA_ENEMY_CASTING_BAR_4 = "Arena Enemy Casting Bar 4", -- Missing translation
	EL_ARENA_ENEMY_CASTING_BAR_5 = "Arena Enemy Casting Bar 5", -- Missing translation
	EL_ARENA_ENEMY_FRAMES = "ArenaEnemyFrames", -- Missing translation
	EL_ARENA_ENEMY_PET_1 = "Arena Enemy Pet 1", -- Missing translation
	EL_ARENA_ENEMY_PET_2 = "Arena Enemy Pet 2", -- Missing translation
	EL_ARENA_ENEMY_PET_3 = "Arena Enemy Pet 3", -- Missing translation
	EL_ARENA_ENEMY_PET_4 = "Arena Enemy Pet 4", -- Missing translation
	EL_ARENA_ENEMY_PET_5 = "Arena Enemy Pet 5", -- Missing translation
	EL_ARENA_PREP_1 = "Arena Prep 1", -- Missing translation
	EL_ARENA_PREP_2 = "Arena Prep 2", -- Missing translation
	EL_ARENA_PREP_3 = "Arena Prep 3", -- Missing translation
	EL_ARENA_PREP_4 = "Arena Prep 4", -- Missing translation
	EL_ARENA_PREP_5 = "Arena Prep 5", -- Missing translation
	EL_ARENA_PREP_FRAMES = "ArenaPrepFrames", -- Missing translation
	EL_ARENA_QUEUE_LIST = "Arena Queue List", -- Missing translation
	EL_ARENA_REGISTRAR = "Arena Registrar", -- Missing translation
	EL_ARENA_TEAM_DETAILS = "Arena Team Details", -- Missing translation
	EL_ARTIFACT_BAR = "Artifact Bar", -- Missing translation
	EL_ARTIFACT_FRAME = "Artifact Frame", -- Missing translation
	EL_AUCTION_CREATION_PROGRESS = "Auction Creation Progress", -- Missing translation
	EL_AUCTION_HOUSE = "Auction House", -- Missing translation
	EL_AUCTION_HOUSE_DRESSING_ROOM = "Auction House Dressing Room", -- Missing translation
	EL_BACKPACK = "Backpack", -- Missing translation
	EL_BACKPACK_BUTTON = "Backpack Button", -- Missing translation
	EL_BAG_1 = "Bag 1", -- Missing translation
	EL_BAG_2 = "Bag 2", -- Missing translation
	EL_BAG_3 = "Bag 3", -- Missing translation
	EL_BAG_4 = "Bag 4", -- Missing translation
	EL_BAG_BUTTON_1 = "Bag Button 1", -- Missing translation
	EL_BAG_BUTTON_2 = "Bag Button 2", -- Missing translation
	EL_BAG_BUTTON_3 = "Bag Button 3", -- Missing translation
	EL_BAG_BUTTON_4 = "Bag Button 4", -- Missing translation
	EL_BAG_BUTTONS = "Bag Buttons", -- Missing translation
	EL_BAG_BUTTONS_VERTICAL = "Bag Buttons - Vertical", -- Missing translation
	EL_BAG_ITEM_SEARCH = "Bag Item Search", -- Missing translation
	EL_BANK = "Bank", -- Missing translation
	EL_BANK_BAG_1 = "Bank Bag 1", -- Missing translation
	EL_BANK_BAG_2 = "Bank Bag 2", -- Missing translation
	EL_BANK_BAG_3 = "Bank Bag 3", -- Missing translation
	EL_BANK_BAG_4 = "Bank Bag 4", -- Missing translation
	EL_BANK_BAG_5 = "Bank Bag 5", -- Missing translation
	EL_BANK_BAG_6 = "Bank Bag 6", -- Missing translation
	EL_BANK_BAG_7 = "Bank Bag 7", -- Missing translation
	EL_BANK_BAG_ITEMS = "Bank Bag Items", -- Missing translation
	EL_BANK_BAG_SLOT_1 = "Bank Bag Slot 1", -- Missing translation
	EL_BANK_BAG_SLOT_2 = "Bank Bag Slot 2", -- Missing translation
	EL_BANK_BAG_SLOT_3 = "Bank Bag Slot 3", -- Missing translation
	EL_BANK_BAG_SLOT_4 = "Bank Bag Slot 4", -- Missing translation
	EL_BANK_BAG_SLOT_5 = "Bank Bag Slot 5", -- Missing translation
	EL_BANK_BAG_SLOT_6 = "Bank Bag Slot 6", -- Missing translation
	EL_BANK_BAG_SLOT_7 = "Bank Bag Slot 7", -- Missing translation
	EL_BANK_BAG_SLOTS = "Bank Bag Slots", -- Missing translation
	EL_BANK_CLEANUP = "Bank Cleanup", -- Missing translation
	EL_BANK_ITEM_SEARCH = "Bank Item Search", -- Missing translation
	EL_BANK_MONEY = "Bank Money", -- Missing translation
	EL_BANK_MONEY_BORDER = "Bank Money Border", -- Missing translation
	EL_BANK_MONEY_COPPER = "Bank Money Copper", -- Missing translation
	EL_BANK_MONEY_GOLD = "Bank Money Gold", -- Missing translation
	EL_BANK_MONEY_INSET = "Bank Money Inset", -- Missing translation
	EL_BANK_MONEY_SILVER = "Bank Money Silver", -- Missing translation
	EL_BARBER_SHOP = "Barber Shop", -- Missing translation
	EL_BATTLE_NET_POPUP_MESSAGE = "Battle.Net Popup Message", -- Missing translation
	EL_BATTLE_PET_TOOLTIP = "BattlePetTooltip", -- Missing translation
	EL_BATTLEFIELD_MINI_MAP = "Battlefield Mini Map", -- Missing translation
	EL_BATTLEGROUND_MINIMAP_BUTTON = "Battleground Minimap Button", -- Missing translation
	EL_BATTLEGROUND_MINIMAP_BUTTON = "Battleground Minimap Button", -- Missing translation
	EL_BATTLEGROUND_MINIMAP_BUTTON_TOOLTIP = "Battleground Minimap Button Tooltip", -- Missing translation
	EL_BATTLEGROUND_QUEUE = "Battleground Queue", -- Missing translation
	EL_BATTLEGROUND_SCOREBOARD = "Battleground Scoreboard", -- Missing translation
	EL_BLACK_MARKET_AUCTION = "Black Market Auction", -- Missing translation
	EL_BONUS_ROLL_FRAME = "Bonus Roll Frame", -- Missing translation
	EL_BONUS_ROLL_ITEM_WON = "BonusRoll Item Won", -- Missing translation
	EL_BONUS_ROLL_MONEY_WON = "BonusRoll Money Won", -- Missing translation
	EL_BOSS_BANNER = "Boss Banner", -- Missing translation
	EL_BOTTOM_FRAME = "Bottom Frame", -- Missing translation
	EL_BOTTOM_LEFT_ACTION_BAR = "Bottom Left Action Bar", -- Missing translation
	EL_BOTTOM_RIGHT_ACTION_BAR = "Bottom Right Action Bar", -- Missing translation
	EL_BREATH_FATIGUE_BAR = "BreathFatigue Bar", -- Missing translation
	EL_CALENDAR = "Calendar", -- Missing translation
	EL_CALENDAR_EVENT = "Calendar Event", -- Missing translation
	EL_CASTING_BAR = "Casting Bar", -- Missing translation
	EL_CHALLENGE_KEYSTONE = "Challenge Keystone", -- Missing translation
	EL_CHANNEL_PULLOUT = "Channel Pullout", -- Missing translation
	EL_CHARACTER_REPUTATION_CURRENCY = "Character / Reputation / Currency", -- Missing translation
	EL_CHAT_CHANNEL_CONFIGURATION = "Chat Channel Configuration", -- Missing translation
	EL_CHAT_EDIT_BOX = "Chat Edit Box", -- Missing translation
	EL_CHAT_EDIT_BOX_LENGTH = "Chat Edit Box Length", -- Missing translation
	EL_CHAT_POPUP_TOOLTIP = "Chat Popup Tooltip", -- Missing translation
	EL_CLASS_ABILITY_PROC = "Class Ability Proc", -- Missing translation
	EL_CLASS_TRAINER = "Class Trainer", -- Missing translation
	EL_CLEAN_UP_BAGS = "Clean Up Bags", -- Missing translation
	EL_COLLECTIONS = "Collections", -- Missing translation
	EL_COLOR_PICKER = "Color Picker", -- Missing translation
	EL_COMBO_POINT_FRAME = "Combo Point Frame", -- Missing translation
	EL_COMMUNITIES = "Communities", -- Missing translation
	EL_CONSOLIDATED_BUFFS = "Consolidated Buffs", -- Missing translation
	EL_CRITERIA_ALERT_1 = "Criteria Alert 1", -- Missing translation
	EL_CRITERIA_ALERT_2 = "Criteria Alert 2", -- Missing translation
	EL_CURRENCY_OPTIONS = "Currency Options", -- Missing translation
	EL_DEATHKNIGHT_RUNE_FRAME = "Deathknight Rune Frame", -- Missing translation
	EL_DIGSITE_COMPLETE_TOAST_FRAME = "Digsite Complete Toast Frame", -- Missing translation
	EL_DRESSING_ROOM = "Dressing Room", -- Missing translation
	EL_DUNGEON_COMPLETION_ALERT = "Dungeon Completion Alert", -- Missing translation
	EL_DUNGEON_FINDER = "Dungeon Finder", -- Missing translation
	EL_DUNGEON_FINDER = "Dungeon Finder", -- Missing translation
	EL_DUNGEON_JOURNAL = "Dungeon Journal", -- Missing translation
	EL_DUNGEON_RAID_FINDER_QUEUE_STATUS = "Dungeon/Raid Finder Queue Status", -- Missing translation
	EL_DUNGEON_READY_DIALOG = "Dungeon Ready Dialog", -- Missing translation
	EL_DUNGEON_READY_POPUP = "Dungeon Ready Popup", -- Missing translation
	EL_DUNGEON_READY_STATUS = "Dungeon Ready Status", -- Missing translation
	EL_DUNGEON_ROLE_CHECK_POPUP = "Dungeon Role Check Popup", -- Missing translation
	EL_DUNGEON_STATUS_BUTTON = "Dungeon Status Button", -- Missing translation
	EL_DUNGEON_STATUS_BUTTON_TOOLTIP = "Dungeon Status Button Tooltip", -- Missing translation
	EL_DURABILITY_FIGURE = "Durability Figure", -- Missing translation
	EL_ENEMY_PET_2 = "Enemy Pet 2", -- Missing translation
	EL_ENEMY_PET_3 = "Enemy Pet 3", -- Missing translation
	EL_ENEMY_PET_BUFFS = "Enemy Pet Buffs", -- Missing translation
	EL_ENEMY_PET_DEBUFFS = "Enemy Pet Debuffs", -- Missing translation
	EL_ENEMY_PET_FRAME = "Enemy Pet Frame", -- Missing translation
	EL_ENEMY_PET_PAD_BUFFS = "Enemy Pet Pad Buffs", -- Missing translation
	EL_ENEMY_PET_PAD_DEBUFFS = "Enemy Pet Pad Debuffs", -- Missing translation
	EL_ERRORS_WARNING_DISPLAY = "Errors & Warning Display", -- Missing translation
	EL_EXPERIENCE_BAR = "Experience Bar", -- Missing translation
	EL_EXTRA_ABILITY_BAR = "Extra Ability Bar", -- Missing translation
	EL_FLAG_CAPTURE_TIMER_BAR = "Flag Capture Timer Bar", -- Missing translation
	EL_FLIGHT_MAP = "Flight Map", -- Missing translation
	EL_FLIGHT_PATHS = "Flight Paths", -- Missing translation
	EL_FLOATING_BATTLE_PET_TOOLTIP = "FloatingBattlePetTooltip", -- Missing translation
	EL_FLOATING_PET_BATTLE_ABILITY_TOOLTIP = "FloatingPetBattleAbilityTooltip", -- Missing translation
	EL_FOCUS = "Focus", -- Missing translation
	EL_FOCUS_BUFFS = "Focus Buffs", -- Missing translation
	EL_FOCUS_CASTING_BAR = "Focus Casting Bar", -- Missing translation
	EL_FOCUS_DEBUFFS = "Focus Debuffs", -- Missing translation
	EL_FOCUS_PVP_ICON = "Focus PVP Icon", -- Missing translation
	EL_FRAMERATE = "Framerate", -- Missing translation
	EL_GAME_MENU = "Game Menu", -- Missing translation
	EL_GARRISON_ARCHITECT = "Garrison Architect", -- Missing translation
	EL_GARRISON_BUILDING_ALERT = "Garrison Building Alert", -- Missing translation
	EL_GARRISON_FOLLOWER_ALERT = "Garrison Follower Alert", -- Missing translation
	EL_GARRISON_MINIMAP_BUTTON = "Garrison Minimap Button", -- Missing translation
	EL_GARRISON_MISSION_ALERT = "Garrison Mission Alert", -- Missing translation
	EL_GARRISON_MISSIONS = "Garrison Missions", -- Missing translation
	EL_GARRISON_MONUMENTS = "Garrison Monuments", -- Missing translation
	EL_GARRISON_REPORT = "Garrison Report", -- Missing translation
	EL_GARRISON_WORK_ORDER = "Garrison Work Order", -- Missing translation
	EL_GEM_SOCKETING = "Gem Socketing", -- Missing translation
	EL_GENERIC_INFO_PANEL_1_LEFT = "Generic Info Panel 1 Left", -- Missing translation
	EL_GENERIC_INFO_PANEL_2_CENTER = "Generic Info Panel 2 Center", -- Missing translation
	EL_GENERIC_INFO_PANEL_3_RIGHT = "Generic Info Panel 3 Right", -- Missing translation
	EL_GM_HELP = "GM Help", -- Missing translation
	EL_GOSSIP = "Gossip", -- Missing translation
	EL_GUILD = "Guild", -- Missing translation
	EL_GUILD_BANK = "Guild Bank", -- Missing translation
	EL_GUILD_BANK_DEPOSIT_BUTTON = "Guild Bank Deposit Button", -- Missing translation
	EL_GUILD_BANK_ITEM_SEACH = "Guild Bank Item Seach", -- Missing translation
	EL_GUILD_BANK_MONEY = "Guild Bank Money", -- Missing translation
	EL_GUILD_BANK_MONEY_COPPER = "Guild Bank Money Copper", -- Missing translation
	EL_GUILD_BANK_MONEY_GOLD = "Guild Bank Money Gold", -- Missing translation
	EL_GUILD_BANK_MONEY_SILVER = "Guild Bank Money Silver", -- Missing translation
	EL_GUILD_BANK_SAVE_BUTTON = "Guild Bank Save Button", -- Missing translation
	EL_GUILD_BANK_TAB_1 = "Guild Bank Tab 1", -- Missing translation
	EL_GUILD_BANK_TAB_2 = "Guild Bank Tab 2", -- Missing translation
	EL_GUILD_BANK_TAB_3 = "Guild Bank Tab 3", -- Missing translation
	EL_GUILD_BANK_TAB_4 = "Guild Bank Tab 4", -- Missing translation
	EL_GUILD_BANK_TAB_5 = "Guild Bank Tab 5", -- Missing translation
	EL_GUILD_BANK_TAB_6 = "Guild Bank Tab 6", -- Missing translation
	EL_GUILD_BANK_TAB_7 = "Guild Bank Tab 7", -- Missing translation
	EL_GUILD_BANK_TAB_8 = "Guild Bank Tab 8", -- Missing translation
	EL_GUILD_BANK_WITHDRAW_BUTTON = "Guild Bank Withdraw Button", -- Missing translation
	EL_GUILD_BANK_WITHDRAW_MONEY = "Guild Bank Withdraw Money", -- Missing translation
	EL_GUILD_BANK_WITHDRAW_MONEY_COPPER = "Guild Bank Withdraw Money Copper", -- Missing translation
	EL_GUILD_BANK_WITHDRAW_MONEY_GOLD = "Guild Bank Withdraw Money Gold", -- Missing translation
	EL_GUILD_BANK_WITHDRAW_MONEY_SILVER = "Guild Bank Withdraw Money Silver", -- Missing translation
	EL_GUILD_CHALLENGE_ACHIEVEMENT_ALERT = "Guild Challenge Achievement Alert", -- Missing translation
	EL_GUILD_CONTROL = "Guild Control", -- Missing translation
	EL_GUILD_FINDER = "Guild Finder", -- Missing translation
	EL_GUILD_INFO = "Guild Info", -- Missing translation
	EL_GUILD_INVITE = "Guild Invite", -- Missing translation
	EL_GUILD_LOG = "Guild Log", -- Missing translation
	EL_GUILD_MEMBER_DETAILS = "Guild Member Details", -- Missing translation
	EL_GUILD_REGISTRAR = "Guild Registrar", -- Missing translation
	EL_HEAL_DAMAGE_NUMBERS = "Heal/Damage Numbers", -- Missing translation
	EL_HONOR_BAR = "Honor Bar", -- Missing translation
	EL_INSPECT = "Inspect", -- Missing translation
	EL_INTERFACE_OPTIONS = "Interface Options", -- Missing translation
	EL_ITEM_UPGRADE = "Item Upgrade", -- Missing translation
	EL_KEY_RING = "Key Ring", -- Missing translation
	EL_KEY_RING_BUTTON = "Key Ring Button", -- Missing translation
	EL_KEYBINDING_OPTIONS = "Keybinding Options", -- Missing translation
	EL_LEAVE_VEHICLE_BUTTON = "Leave Vehicle Button", -- Missing translation
	EL_LEFT_GRYPHON = "Left Gryphon", -- Missing translation
	EL_LEVEL_UP_DISPLAY = "Level Up Display", -- Missing translation
	EL_LEVEL_UP_DISPLAY = "LevelUpDisplay", -- Missing translation
	EL_LOOKING_FOR_RAID = "Looking For Raid", -- Missing translation
	EL_LOOT = "Loot", -- Missing translation
	EL_LOOT_ROLL_1 = "Loot Roll 1", -- Missing translation
	EL_LOOT_ROLL_2 = "Loot Roll 2", -- Missing translation
	EL_LOOT_ROLL_3 = "Loot Roll 3", -- Missing translation
	EL_LOOT_ROLL_4 = "Loot Roll 4", -- Missing translation
	EL_LOOT_WON_ALERT_FRAME_1 = "Loot Won Alert Frame 1", -- Missing translation
	EL_LOOT_WON_ALERT_FRAME1 = "Loot Won Alert Frame1", -- Missing translation
	EL_LOOT_WON_ALERT_FRAME10 = "Loot Won Alert Frame10", -- Missing translation
	EL_LOOT_WON_ALERT_FRAME2 = "Loot Won Alert Frame2", -- Missing translation
	EL_LOOT_WON_ALERT_FRAME3 = "Loot Won Alert Frame3", -- Missing translation
	EL_LOOT_WON_ALERT_FRAME4 = "Loot Won Alert Frame4", -- Missing translation
	EL_LOOT_WON_ALERT_FRAME5 = "Loot Won Alert Frame5", -- Missing translation
	EL_LOOT_WON_ALERT_FRAME6 = "Loot Won Alert Frame6", -- Missing translation
	EL_LOOT_WON_ALERT_FRAME7 = "Loot Won Alert Frame7", -- Missing translation
	EL_LOOT_WON_ALERT_FRAME8 = "Loot Won Alert Frame8", -- Missing translation
	EL_LOOT_WON_ALERT_FRAME9 = "Loot Won Alert Frame9", -- Missing translation
	EL_LOSS_OF_CONTROL = "Loss Of Control", -- Missing translation
	EL_MACRO_NAME_ICON = "Macro Name & Icon", -- Missing translation
	EL_MACRO_OPTIONS = "Macro Options", -- Missing translation
	EL_MACROS = "Macros", -- Missing translation
	EL_MAGE_ARCANE_CHARGES_POWER_FRAME = "Mage Arcane Charges Power Frame", -- Missing translation
	EL_MAILBOX = "Mailbox", -- Missing translation
	EL_MAIN_BAR = "Main Bar", -- Missing translation
	EL_MAP_COORDINATES = "Map Coordinates", -- Missing translation
	EL_MAP_LEVEL = "Map Level", -- Missing translation
	EL_MAP_OPTIONS = "Map Options", -- Missing translation
	EL_MAP_TRACK_QUEST = "Map Track Quest", -- Missing translation
	EL_MAX_LEVEL_BAR_FILLER = "Max Level Bar Filler", -- Missing translation
	EL_MERCHANT = "Merchant", -- Missing translation
	EL_MICRO_BAGS_BAR = "Micro Bags Bar", -- Missing translation
	EL_MICRO_MENU = "Micro Menu", -- Missing translation
	EL_MICRO_MENU_SPLIT = "Micro Menu - Split", -- Missing translation
	EL_MICRO_MENU_VERTICAL = "Micro Menu - Vertical", -- Missing translation
	EL_MINIMAP = "Minimap", -- Missing translation
	EL_MINIMAP_BORDER_TEXTURE = "Minimap Border Texture", -- Missing translation
	EL_MINIMAP_CALENDAR_BUTTON = "Minimap Calendar Button", -- Missing translation
	EL_MINIMAP_CLOCK_BUTTON = "Minimap Clock Button", -- Missing translation
	EL_MINIMAP_DUNGEON_DIFFICULTY = "Minimap Dungeon Difficulty", -- Missing translation
	EL_MINIMAP_GUILD_GROUP_FLAG = "Minimap Guild Group Flag", -- Missing translation
	EL_MINIMAP_MAIL_NOTIFICATION = "Minimap Mail Notification", -- Missing translation
	EL_MINIMAP_NORTH_INDICATOR = "Minimap North Indicator", -- Missing translation
	EL_MINIMAP_QUEUE_STATUS_BUTTON = "Minimap Queue Status Button", -- Missing translation
	EL_MINIMAP_ROUND_BORDER = "Minimap Round Border", -- Missing translation
	EL_MINIMAP_TOP_BORDER = "Minimap Top Border", -- Missing translation
	EL_MINIMAP_TRACKING_BUTTON = "Minimap Tracking Button", -- Missing translation
	EL_MINIMAP_WORLD_MAP_BUTTON = "Minimap World Map Button", -- Missing translation
	EL_MINIMAP_ZONE_TEXT = "Minimap Zone Text", -- Missing translation
	EL_MINIMAP_ZOOM_IN_BUTTON = "Minimap Zoom In Button", -- Missing translation
	EL_MINIMAP_ZOOM_OUT_BUTTON = "Minimap Zoom Out Button", -- Missing translation
	EL_MISSING_LOOT_FRAME = "Missing Loot Frame", -- Missing translation
	EL_MONEY_WON_FRAME1 = "Money Won Frame1", -- Missing translation
	EL_MONEY_WON_FRAME2 = "Money Won Frame2", -- Missing translation
	EL_MONEY_WON_FRAME3 = "Money Won Frame3", -- Missing translation
	EL_MONEY_WON_FRAME4 = "Money Won Frame4", -- Missing translation
	EL_MONEY_WON_FRAME5 = "Money Won Frame5", -- Missing translation
	EL_MONK_CHI_FRAME = "Monk Chi Frame", -- Missing translation
	EL_MONK_STAGGER_FRAME = "Monk Stagger Frame", -- Missing translation
	EL_MOVE_ANYTHING_FRAME_EDITOR_CONFIG = "MoveAnything Frame Editor Config", -- Missing translation
	EL_MOVE_ANYTHING_GAME_MENU_BUTTON = "MoveAnything Game Menu Button", -- Missing translation
	EL_MOVE_ANYTHING_NUDGER = "MoveAnything Nudger", -- Missing translation
	EL_MOVE_ANYTHING_WINDOW = "MoveAnything Window", -- Missing translation
	EL_NAVAL_OPERATIONS = "Naval Operations", -- Missing translation
	EL_OBJECTIVES_BANNER_FRAME = "Objectives Banner Frame", -- Missing translation
	EL_OBJECTIVES_WINDOW = "Objectives Window", -- Missing translation
	EL_OBJECTIVES_WINDOW_SCALE = "Objectives Window Scale", -- Missing translation
	EL_OPEN_MAIL = "Open Mail", -- Missing translation
	EL_ORDER_HALL_COMMAND_BAR = "Order Hall Command Bar", -- Missing translation
	EL_ORDER_HALL_MISSIONS = "Order Hall Missions", -- Missing translation
	EL_ORDER_HALL_TALENT_ALERT = "Order Hall Talent Alert", -- Missing translation
	EL_ORDER_HALL_TALENTS = "Order Hall Talents", -- Missing translation
	EL_OTHER_RAIDS = "Other Raids", -- Missing translation
	EL_PALADIN_POWER_FRAME = "Paladin Power Frame", -- Missing translation
	EL_PARTY_MEMBER_1 = "Party Member 1", -- Missing translation
	EL_PARTY_MEMBER_1_DEBUFFS = "Party Member 1 Debuffs", -- Missing translation
	EL_PARTY_MEMBER_2 = "Party Member 2", -- Missing translation
	EL_PARTY_MEMBER_2_DEBUFFS = "Party Member 2 Debuffs", -- Missing translation
	EL_PARTY_MEMBER_3 = "Party Member 3", -- Missing translation
	EL_PARTY_MEMBER_3_DEBUFFS = "Party Member 3 Debuffs", -- Missing translation
	EL_PARTY_MEMBER_4 = "Party Member 4", -- Missing translation
	EL_PARTY_MEMBER_4_DEBUFFS = "Party Member 4 Debuffs", -- Missing translation
	EL_PARTY_PET_1 = "Party Pet 1", -- Missing translation
	EL_PARTY_PET_2 = "Party Pet 2", -- Missing translation
	EL_PARTY_PET_3 = "Party Pet 3", -- Missing translation
	EL_PARTY_PET_4 = "Party Pet 4", -- Missing translation
	EL_PASS_BUTTON = "Pass Button", -- Missing translation
	EL_PET = "Pet", -- Missing translation
	EL_PET_ACTION_BAR = "Pet Action Bar", -- Missing translation
	EL_PET_ACTION_BAR_VERTICAL = "Pet Action Bar - Vertical", -- Missing translation
	EL_PET_BATTLE_PRIMARY_ABILITY_TOOLTIP = "PetBattle Primary Ability Tooltip", -- Missing translation
	EL_PET_BATTLE_PRIMARY_UNIT_TOOLTIP = "PetBattle Primary Unit Tooltip", -- Missing translation
	EL_PET_CASTING_BAR = "Pet Casting Bar", -- Missing translation
	EL_PET_DEBUFFS = "Pet Debuffs", -- Missing translation
	EL_PET_SELECTION_FRAME = "Pet Selection Frame", -- Missing translation
	EL_PET_STABLE = "Pet Stable", -- Missing translation
	EL_PLAYER = "Player", -- Missing translation
	EL_PLAYER_ALTERNATIVE_POWER_BAR = "Player Alternative Power Bar", -- Missing translation
	EL_PLAYER_ATTACK_ICON = "Player Attack Icon", -- Missing translation
	EL_PLAYER_ATTACK_ICON_S_BACKGROUND = "Player Attack Icon's Background", -- Missing translation
	EL_PLAYER_ATTACK_ICON_S_GLOW = "Player Attack Icon's Glow", -- Missing translation
	EL_PLAYER_BUFFS_CONSOLIDATED_BUFFS_TOOLTIP = "Player Buffs - Consolidated Buffs Tooltip", -- Missing translation
	EL_PLAYER_BUFFS_DEFAULT = "Player Buffs Default", -- Missing translation
	EL_PLAYER_BUFFS_FROM_RIGHT_TO_LEFT = "Player Buffs From Right to Left", -- Missing translation
	EL_PLAYER_DEBUFFS_DEFAULT = "Player Debuffs Default", -- Missing translation
	EL_PLAYER_DEBUFFS_FROM_RIGHT_TO_LEFT = "Player Debuffs From Right to Left", -- Missing translation
	EL_PLAYER_GROUP_INDICATOR = "Player Group Indicator", -- Missing translation
	EL_PLAYER_LEADER_ICON = "Player Leader Icon", -- Missing translation
	EL_PLAYER_MASTER_ICON = "Player Master Icon", -- Missing translation
	EL_PLAYER_PET_FRAME = "Player Pet Frame", -- Missing translation
	EL_PLAYER_PVP_ICON = "Player PVP Icon", -- Missing translation
	EL_PLAYER_REST_ICON = "Player Rest Icon", -- Missing translation
	EL_PLAYER_REST_ICON_S_GLOW = "Player Rest Icon's Glow", -- Missing translation
	EL_PLAYER_STATUS_GLOW = "Player Status Glow", -- Missing translation
	EL_PLAYER_STATUS_TEXTURE = "Player Status Texture", -- Missing translation
	EL_POWER_ABILITY_BAR = "Power Ability Bar", -- Missing translation
	EL_PRESTIGE_BANNER = "Prestige Banner", -- Missing translation
	EL_PVP_READY_DIALOG = "PVP Ready Dialog", -- Missing translation
	EL_PVP_READY_POPUP = "PVP Ready Popup", -- Missing translation
	EL_PVP_WINDOW = "PVP Window", -- Missing translation
	EL_QUEST_CHOICE_FRAME = "Quest Choice Frame", -- Missing translation
	EL_QUEST_DETAILS = "Quest Details", -- Missing translation
	EL_QUEST_DETAILS = "Quest Details", -- Missing translation
	EL_QUEST_LOG_NPC_MODEL = "Quest Log NPC Model", -- Missing translation
	EL_QUEST_OFFER_RETURN = "Quest Offer / Return", -- Missing translation
	EL_QUEST_TALKING_HEAD_FRAME = "Quest Talking Head Frame", -- Missing translation
	EL_QUEST_TIMER = "Quest Timer", -- Missing translation
	EL_QUICK_JOIN_TOAST = "Quick Join Toast", -- Missing translation
	EL_QUICK_JOIN_TOAST_2 = "Quick Join Toast 2", -- Missing translation
	EL_QUICK_JOIN_TOAST_BUTTON = "Quick Join Toast Button", -- Missing translation
	EL_RAID_BOSS_EMOTE_DISPLAY = "Raid Boss Emote Display", -- Missing translation
	EL_RAID_BOSS_HEALTH_BAR_1 = "Raid Boss Health Bar 1", -- Missing translation
	EL_RAID_BOSS_HEALTH_BAR_2 = "Raid Boss Health Bar 2", -- Missing translation
	EL_RAID_BOSS_HEALTH_BAR_3 = "Raid Boss Health Bar 3", -- Missing translation
	EL_RAID_BOSS_HEALTH_BAR_4 = "Raid Boss Health Bar 4", -- Missing translation
	EL_RAID_BOSS_HEALTH_BAR_5 = "Raid Boss Health Bar 5", -- Missing translation
	EL_RAID_BOSS_POWER_BAR_1 = "Raid Boss Power Bar 1", -- Missing translation
	EL_RAID_BOSS_POWER_BAR_2 = "Raid Boss Power Bar 2", -- Missing translation
	EL_RAID_BOSS_POWER_BAR_3 = "Raid Boss Power Bar 3", -- Missing translation
	EL_RAID_BOSS_POWER_BAR_4 = "Raid Boss Power Bar 4", -- Missing translation
	EL_RAID_BOSS_POWER_BAR_5 = "Raid Boss Power Bar 5", -- Missing translation
	EL_RAID_FINDER = "Raid Finder", -- Missing translation
	EL_RAID_FRAME_BUFF_TOOLTIPS = "Raid Frame Buff Tooltips", -- Missing translation
	EL_RAID_FRAME_DEBUFF_TOOLTIPS = "Raid Frame Debuff Tooltips", -- Missing translation
	EL_RAID_GROUP_1 = "Raid Group 1", -- Missing translation
	EL_RAID_GROUP_2 = "Raid Group 2", -- Missing translation
	EL_RAID_GROUP_3 = "Raid Group 3", -- Missing translation
	EL_RAID_GROUP_4 = "Raid Group 4", -- Missing translation
	EL_RAID_GROUP_5 = "Raid Group 5", -- Missing translation
	EL_RAID_GROUP_6 = "Raid Group 6", -- Missing translation
	EL_RAID_GROUP_7 = "Raid Group 7", -- Missing translation
	EL_RAID_GROUP_8 = "Raid Group 8", -- Missing translation
	EL_RAID_MANAGER = "Raid Manager", -- Missing translation
	EL_RAID_MANAGER_TOGGLE_BUTTON = "Raid Manager Toggle Button", -- Missing translation
	EL_RAID_ROLE_POPUP = "Raid Role Popup", -- Missing translation
	EL_RAID_UNIT_FRAMES = "Raid Unit Frames", -- Missing translation
	EL_RAID_WARNINGS = "Raid Warnings", -- Missing translation
	EL_READING_MATERIALS = "Reading Materials", -- Missing translation
	EL_READY_CHECK = "Ready Check", -- Missing translation
	EL_REFORGE = "Reforge", -- Missing translation
	EL_REPORT_PLAYER_CHEATING = "Report Player Cheating", -- Missing translation
	EL_REPORT_PLAYER_NAME = "Report Player Name", -- Missing translation
	EL_REPUTATION_DETAILS = "Reputation Details", -- Missing translation
	EL_REPUTATION_TRACKER_BAR = "Reputation Tracker Bar", -- Missing translation
	EL_RETURN_TO_GRAVEYARD_BUTTON = "Return to Graveyard Button", -- Missing translation
	EL_RIGHT_ACTION_BAR = "Right Action Bar", -- Missing translation
	EL_RIGHT_ACTION_BAR = "Right Action Bar", -- Missing translation
	EL_RIGHT_ACTION_BAR_2 = "Right Action Bar 2", -- Missing translation
	EL_RIGHT_ACTION_BAR_2 = "Right Action Bar 2", -- Missing translation
	EL_RIGHT_ACTION_BAR_2_HORIZONTAL = "Right Action Bar 2 - Horizontal", -- Missing translation
	EL_RIGHT_ACTION_BAR_HORIZONTAL = "Right Action Bar - Horizontal", -- Missing translation
	EL_RIGHT_GRYPHON = "Right Gryphon", -- Missing translation
	EL_SCENARIO_COMPLETION_ALERT_1 = "Scenario Completion Alert 1", -- Missing translation
	EL_SCENARIO_COMPLETION_ALERT_2 = "Scenario Completion Alert 2", -- Missing translation
	EL_SHAMAN_TOTEM_FRAME = "Shaman Totem Frame", -- Missing translation
	EL_SHIPYARD_FOLLOWER_ALERT = "Shipyard Follower Alert", -- Missing translation
	EL_SHIPYARD_MISSION_ALERT = "Shipyard Mission Alert", -- Missing translation
	EL_SOCIAL_FRIENDS_WHO_GUILD_CHAT_RAID = "Social - Friends / Who / Guild / Chat / Raid", -- Missing translation
	EL_SOUND_VOICE_OPTIONS = "Sound & Voice Options", -- Missing translation
	EL_SPECIALIZATION_TALENTS_GLYPHS = "Specialization / Talents / Glyphs", -- Missing translation
	EL_SPELLBOOK_PROFESSIONS = "Spellbook / Professions", -- Missing translation
	EL_STANCE_BUTTONS = "Stance Buttons", -- Missing translation
	EL_STANCE_BUTTONS_VERTICAL = "Stance Buttons - Vertical", -- Missing translation
	EL_START_SPLASH = "StartSplash", -- Missing translation
	EL_STATIC_POPUP_1 = "Static Popup 1", -- Missing translation
	EL_STATIC_POPUP_2 = "Static Popup 2", -- Missing translation
	EL_STATIC_POPUP_3 = "Static Popup 3", -- Missing translation
	EL_STATIC_POPUP_4 = "Static Popup 4", -- Missing translation
	EL_STORE_MODEL_PREVIEW = "Store Model Preview", -- Missing translation
	EL_STORE_PURCHASE_ALERT = "Store Purchase Alert", -- Missing translation
	EL_STREAMING_DOWNLOAD_ICON = "Streaming Download Icon", -- Missing translation
	EL_TABARD_DESIGN = "Tabard Design", -- Missing translation
	EL_TALENTS_GLYPHS = "Talents / Glyphs", -- Missing translation
	EL_TARGET = "Target", -- Missing translation
	EL_TARGET_ALTERNATIVE_POWER_BAR = "Target Alternative Power Bar", -- Missing translation
	EL_TARGET_BUFFS = "Target Buffs", -- Missing translation
	EL_TARGET_CASTING_BAR = "Target Casting Bar", -- Missing translation
	EL_TARGET_COMBO_POINTS_DISPLAY = "Target Combo Points Display", -- Missing translation
	EL_TARGET_DEBUFFS = "Target Debuffs", -- Missing translation
	EL_TARGET_OF_FOCUS = "Target of Focus", -- Missing translation
	EL_TARGET_OF_FOCUS_DEBUFFS = "Target of Focus Debuffs", -- Missing translation
	EL_TARGET_OF_TARGET = "Target of Target", -- Missing translation
	EL_TARGET_OF_TARGET_DEBUFFS = "Target of Target Debuffs", -- Missing translation
	EL_TARGET_PVP_ICON = "Target PVP Icon", -- Missing translation
	EL_TARGET_THREAT_INDICATOR = "Target Threat Indicator", -- Missing translation
	EL_TICKET_STATUS = "Ticket Status", -- Missing translation
	EL_TICKET_STATUS_TUTORIAL = "Ticket Status Tutorial", -- Missing translation
	EL_TIME_ALERT_POPUP_MESSAGE = "Time Alert Popup Message", -- Missing translation
	EL_TIMER_TRACKER = "Timer tracker", -- Missing translation
	EL_TOOLTIP = "Tooltip", -- Missing translation
	EL_TOOLTIP_BAG_ITEM = "Tooltip - Bag Item", -- Missing translation
	EL_TOOLTIP_GUILD_BANK_ITEM = "Tooltip - Guild Bank Item", -- Missing translation
	EL_TOP_CENTER_STATUS_DISPLAY = "Top Center Status Display", -- Missing translation
	EL_TOP_LEFT_ART = "Top Left Art", -- Missing translation
	EL_TOP_LEFT_CENTER = "Top Left Center", -- Missing translation
	EL_TOP_RIGHT_ART = "Top Right Art", -- Missing translation
	EL_TOTEM_FRAME = "Totem Frame", -- Missing translation
	EL_TRADE = "Trade", -- Missing translation
	EL_TRADE_SKILLS = "Trade Skills", -- Missing translation
	EL_TRANSMOGRIFICATION = "Transmogrification", -- Missing translation
	EL_TUTORIALS_ALERT_BUTTON = "Tutorials Alert Button", -- Missing translation
	EL_UNSAVED_TALENT_CHANGES_ALERT = "Unsaved Talent Changes Alert", -- Missing translation
	EL_VEHICLE_ACTION_BAR = "Vehicle Action Bar", -- Missing translation
	EL_VEHICLE_BAR = "Vehicle Bar", -- Missing translation
	EL_VEHICLE_EXPERIENCE_BAR = "Vehicle Experience Bar", -- Missing translation
	EL_VEHICLE_HEALTH_BAR = "Vehicle Health Bar", -- Missing translation
	EL_VEHICLE_LEAVE_FRAME = "Vehicle Leave Frame", -- Missing translation
	EL_VEHICLE_MICRO_BAR = "Vehicle Micro Bar", -- Missing translation
	EL_VEHICLE_POWER_BAR = "Vehicle Power Bar", -- Missing translation
	EL_VEHICLE_SEAT_INDICATOR = "Vehicle Seat Indicator", -- Missing translation
	EL_VIDEO_OPTIONS = "Video Options", -- Missing translation
	EL_VOICE_CHAT_TALKERS = "Voice Chat Talkers", -- Missing translation
	EL_VOID_STORAGE = "Void Storage", -- Missing translation
	EL_WARLOCK_POWER_FRAME = "Warlock Power Frame", -- Missing translation
	EL_WEATHER = "Weather", -- Missing translation
	EL_WORK_ORDER = "Work Order", -- Missing translation
	EL_WORLD_MAP = "World Map", -- Missing translation
	EL_WORLD_QUEST_COMPLETE_ALERT = "World Quest Complete Alert", -- Missing translation
	EL_ZONE_MINIMAP = "Zone Minimap", -- Missing translation
	EL_ZONING_SUBZONE_TEXT = "Zoning Subzone Text", -- Missing translation
	EL_ZONING_ZONE_TEXT = "Zoning Zone Text", -- Missing translation
	ELEMENT_NOT_FOUND = "Elemento de interfaz de usuario que no se encuentra",
	ELEMENT_NOT_FOUND_NAMED = "Elemento de interfaz de usuario no encontrado: %s",
	ENABLED = "Enabled", -- Missing translation
	ERROR_FRAME_FAILED = "Se produjo un error al sincronizar %s. Reiniciar el marco y volver a cargar antes de modificarlo de nuevo podría resolver el problema. Puede deshabilitar este mensaje en las opciones. Si el problema persiste, por favor informar lo siguiente al autor: %s %s %s",
	ERROR_MODULE_FAILED = "Ha ocurrido un error mientras se ajusta %s para %s. Puede deshabilitar este mensaje en las opciones. Si el problema persiste, por favor informa del siguiente al autor: %s %s %s %s",
	ERROR_NOT_A_TABLE = "\"%s\" es un tipo no soportado",
	EXPORT = "Export", -- Missing translation
	FE_FORCED_LOCK_POSITION_CONFIRM = "Forzar bloqueo de la posición? Haga clic de nuevo dentro de 5 segundos para confirmar",
	FE_FORCED_LOCK_POSITION_TOOLTIP = "Sobrescribe método del elemento SetPoint,\nreemplazándolo con un código auxiliar vacío\n\nPuede causar una corrupción si el elemento está protegido\ny el código auxiliar se llama durante el combate\n\nRequiere volver a cargar o relog después de deseleccionarlo para\nrestablecer el método original de SetPoint",
	FE_GROUP_RESET_CONFIRM = "¿Restablecer Grupo  %i ? Haga clic de nuevo dentro de 5 segundos para confirmar",
	FE_GROUPS_TOOLTIP = "Grupo %i",
	FE_UNREGISTER_ALL_EVENTS_CONFIRM = "Anular el registro de todos los eventos? Haga clic de nuevo dentro de 5 segundos para confirmar",
	FE_UNREGISTER_ALL_EVENTS_TOOLTIP = "Anula el registro de los eventos que el marco está escuchando,\ndibujando la imagen inerte\n\nVolver a habilitar los eventos registrados requerirá volver a cargar\nrelog o después de deseleccionar la casilla de verificación",
	FORCE_LOCK_POSITION = "Force lock position", -- Missing translation
	FRAME = "Frame", -- Missing translation
	FRAME_NO_FRAME_EDITOR = "Editores de Marco está desactivado para %s",
	FRAME_ONLY_ONCE_OPENED = "Sólo puede interactuar con %s una vez se ha mostrado",
	FRAME_ONLY_WHEN_BANK_IS_OPEN = "sólo puede interactúar con %s mientras el banco está abierto",
	FRAME_ONLY_WHEN_VOIDSTORAGE_IS_OPEN = "Sólo puede interactuar %s está abierto",
	FRAME_PROTECTED_DURING_COMBAT = "No puede interactuar con %s durante el combate",
	FRAME_UNPOSITIONED = "%s está actualmente no posicionado y no se puede mover hasta que esté",
	FRAME_VISIBILITY_ONLY = "%s sólo se puede ocultar",
	GROUPS = "Groups", -- Missing translation
	HEIGHT = "Height", -- Missing translation
	HIDDEN = "Hidden", -- Missing translation
	HIDE_LAYER = "Hide Layer", -- Missing translation
	HIGHLIGHT = "Highlight", -- Missing translation
	HOOKALLOWED = "Habilita si MoveAnything fijará Crear marco.\n\nRequiere recargar para tener efecto.",
	HOOKALLOWEDNO = "Desactivar fijación de la creación de marco",
	IMPORT = "Import", -- Missing translation
	LIST_HEADING_CATEGORY_AND_FRAMES = "Categorías y Marcos",
	LIST_HEADING_HIDE = "Oculta",
	LIST_HEADING_MOVER = "Encabezado Mover",
	LIST_HEADING_SEARCH_RESULTS = "Resultados de la búsqueda: %i",
	MA_OPT_ALWAYS_SHOW_NUDGER = "Show Nudger with main window", -- Missing translation
	MA_OPT_ALWAYS_SHOW_NUDGER_TOOLTIP = "Enable to show the nudger with the main window\n\nBy default the Nudger is only shown when interacting with frames.", -- Missing translation
	MA_OPT_CLOSE_GUI_ON_ESCAPE = "Escape key closes main window", -- Missing translation
	MA_OPT_DISABLE_ERROR_MESSAGES = "Disable error messages", -- Missing translation
	MA_OPT_DISABLE_ERROR_MESSAGES_TOOLTIP = "Toggles printing of error messages on/off.", -- Missing translation
	MA_OPT_DONT_HOOK_CREATE_FRAME = "Disable frame creation hook", -- Missing translation
	MA_OPT_DONT_HOOK_CREATE_FRAME_TOOLTIP = "Toggles if MoveAnything will hook CreateFrame.\n\nRequires reload to take effect.", -- Missing translation
	MA_OPT_DONT_SEARCH_FRAME_NAMES = "Don't search frame names", -- Missing translation
	MA_OPT_DONT_SEARCH_FRAME_NAMES_TOOLTIP = "Disables searching of actual frame names.", -- Missing translation
	MA_OPT_DONT_SYNC_WHEN_LEAVING_COMBAT = "Disable sync when leaving combat", -- Missing translation
	MA_OPT_DONT_SYNC_WHEN_LEAVING_COMBAT_TOOLTIP = "Toggles if MoveAnything will synchronize pending frames when leaving combat.\n\nDisabling this may result in protected frames requiring a manual sync when leaving combat.", -- Missing translation
	MA_OPT_EXPORT_PROFILE = "Export Profile", -- Missing translation
	MA_OPT_FRAME_LIST_ROWS = "List rows", -- Missing translation
	MA_OPT_IMPORT_PROFILE = "Import Profile", -- Missing translation
	MA_OPT_NO_BAGS = "Disable bag container hook", -- Missing translation
	MA_OPT_NO_BAGS_TOOLTIP = "Toggles if MoveAnything will hook containers.\n\nThis should be checked if you use another addon to move your bags.", -- Missing translation
	MA_OPT_NO_MMMW = "Disable Minimap mousewheel zoom", -- Missing translation
	MA_OPT_NO_MMMW_TOOLTIP = "Toggles Minimap mousewheel zoom on/off.\n\nRequires reload to take effect.", -- Missing translation
	MA_OPT_PLAY_SOUND = "Play sound", -- Missing translation
	MA_OPT_PLAY_SOUND_TOOLTIP = "Toggles if MoveAnything should play a sound when opening and closing the main window.", -- Missing translation
	MA_OPT_PROFILE = "Profile", -- Missing translation
	MA_OPT_PROFILE_ADD_TOOLTIP = "Add new", -- Missing translation
	MA_OPT_PROFILE_DELETE_TOOLTIP = "Delete", -- Missing translation
	MA_OPT_PROFILE_EXPORT = "Export", -- Missing translation
	MA_OPT_PROFILE_EXPORT_IMPORT_LABEL = "%s Profile", -- Missing translation
	MA_OPT_PROFILE_FROM = "From", -- Missing translation
	MA_OPT_PROFILE_IMPORT = "Import", -- Missing translation
	MA_OPT_PROFILE_NO_PROFILES = "No profiles available", -- Missing translation
	MA_OPT_PROFILE_PROFILE_NOT_MODIFIED = "No profile has modified this frame", -- Missing translation
	MA_OPT_PROFILE_PROFILE_NOT_MODIFIED_PLURAL = "No profiles has modified this frame", -- Missing translation
	MA_OPT_PROFILE_RENAME_TOOLTIP = "Rename", -- Missing translation
	MA_OPT_PROFILE_SAVE_AS_TOOLTIP = "Save as", -- Missing translation
	MA_OPT_PROFILE_TO = "To", -- Missing translation
	MA_OPT_RESET_ALL = "Reset All", -- Missing translation
	MA_OPT_RESET_ALL_TOOLTIP = "Reset all\n\nReset MoveAnything to default settings. Deletes all frame settings, as well as the custom frame list", -- Missing translation
	MA_OPT_RESET_PROFILE_TOOLTIP = "Reset profile\n\nResets the profile, deleting all stored frame settings for this profile.", -- Missing translation
	MA_OPT_ROWS_SLIDER = "# of rows", -- Missing translation
	MA_OPT_SHOW_TOOLTIPS = "Show tooltips", -- Missing translation
	MA_OPT_SHOW_TOOLTIPS_TOOLTIP = "Toggles display of tooltips on/off\n\nPressing Shift when mousing over elements will reverse tooltip display behavior.", -- Missing translation
	MA_OPT_SQUARE_MM = "Enable square Minimap", -- Missing translation
	MA_OPT_SQUARE_MM_TOOLTIP = "Toggles square MiniMap on/off.\n\nHide \"Round Border\" in the \"Minimap\" category to get rid of the overlaying border.", -- Missing translation
	MA_OPT_TEXT_STRING = "Text String", -- Missing translation
	MA_OPT_VERSION = "Version", -- Missing translation
	MOUSEOVER = "Mouseover", -- Missing translation
	MOVER = "Mover", -- Missing translation
	NAME = "Name", -- Missing translation
	NO_NAMED_FRAMES_FOUND = "No se encontraron los elementos nombrados",
	NOMMWP = "Cambia zoom con rueda del ratón del minimapa  on/off.\n\nRequiere recargar para tener efecto.",
	NOMMWPNO = "Deshabilitar zoom con la rueda del ratón del minimapa ",
	NUDGER1 = "Mostrar Recordatorio con la ventana principal",
	OF = "of", -- Missing translation
	ONLY_ONCE_CREATED = "%s sólo puede ser modificado después de que ha sido creado",
	OPTBAGS1 = "Cambia si se fijan los contenedores.\n\nEsto se debe revisar si se utiliza otro addon para mover sus bolsas.",
	OPTBAGSTOOLTIP = "Deshabilitar fijación de bolsas contenedoras",
	OPTIONTOOLTIP1 = "Activar para mostrar el Recordatorio con la ventana principal\n\nPor defecto, el Recordatorio sólo se muestra cuando se interactúa con los marcos.",
	OPTIONTOOLTIP2 = "Alterna la presentación de información de herramientas on/off\n\nSi pulsa Mayús al pasar el ratón sobre los elementos invertirá el comportamiento de información de herramientas de visualización.",
	OVERLAY = "Overlay", -- Missing translation
	PARENT = "Parent", -- Missing translation
	PARENTS_PARENT = "Parent's Parent", -- Missing translation
	PLAYSOUND = "Reproducir sonido",
	PLAYSOUNDS = "cambia si MoveAnything debe reproducir un sonido al abrir y cerrar la ventana principal.",
	POSITION = "Position", -- Missing translation
	PROFILE_ADD_TEXT = "Introduzca nuevo nombre de perfil",
	PROFILE_ALREADY_EXISTS = "Perfil  \"%s\" ya existe",
	PROFILE_CANT_DELETE_CURRENT_IN_COMBAT = "No se puede eliminar el perfil actual durante el combate",
	PROFILE_CANT_DELETE_DEFAULT = "El perfil por defecto no se puede eliminar",
	PROFILE_CURRENT = "Perfil Actual",
	PROFILE_DELETE_TEXT = "¿Borrar Perfil \"%s\"?",
	PROFILE_DELETED = "Perfil borrado: %s",
	PROFILE_EXPORTED = "\"%s\" exportado a \"%s\"",
	PROFILE_IMPORTED = "\"%s\" ha sido importado a \"%s\"",
	PROFILE_RENAME_TEXT = "Escribe nuevo nomre para \"%s\"",
	PROFILE_RESET_CONFIRM = "MoveAnything: Borrar todos los cuadros en el perfil actual?",
	PROFILE_SAVE_AS_TEXT = "Escriba nuevo nombre del perfil",
	PROFILE_UNKNOWN = "Perfil Desconocido: %s",
	PROFILES = "Perfiles",
	PROFILES_CANT_SWITCH_DURING_COMBAT = "Los perfiles no se pueden cambiar durante el combate",
	RENAME = "Renombrar",
	RESET = "Reset", -- Missing translation
	RESET = "Reset", -- Missing translation
	RESET_ALL_CONFIRM = "MoveAnything: Restablecer MoveAnything al estado de instalación?\n\nAdvertencia: esto eliminará todos los ajustes del marco y vaciar á la lista marco personalizado.",
	RESET_FRAME_CONFIRM = "Restaurar %s? Pulse de nuevo el plazo de 5 segundos para confirmar",
	RESETALL1 = "Restablecer todo\n\nRestablecer a la configuración predeterminada. Borra todas las configuraciones de marco, así como la lista de marco personalizado",
	RESETPROFILE1 = "Restaurar el perfil\n\nRestablece el perfil, borrar todos los ajustes almacenados marco para este perfil.",
	RESETTING_FRAME = "Restableciendo %s",
	REVERT = "Revert", -- Missing translation
	SAFE = "Safe", -- Missing translation
	SAVE = "Guadar",
	SAVEAS = "Guardar como",
	SCALE = "Scale", -- Missing translation
	SCALE = "Scale", -- Missing translation
	SEARCH_TEXT = "Buscar",
	SHOW = "Show", -- Missing translation
	SHOWTOOLTIPS = "Mostar información de herramientas.",
	SQUARMAP = "Cambia MiniMap cuadrado on/off.\n\nOculta \"Borde Redondo\" en el \"minimapa\" categoría para deshacerse de la superposición.de el borde ",
	SQUARMAPNO = "habilitar Minimpa Cuadrado",
	STRATA = "Strata", -- Missing translation
	SYNC = "Sync", -- Missing translation
	TO = "to", -- Missing translation
	TOGGLE_CATEGORIES_BUTTON_TOOLTIP = "Toggle all categories", -- Missing translation
	TOGGLE_FRAME_EDITORS_BUTTON_TOOLTIP = "Toggle visibility on frame editors", -- Missing translation
	TOGGLE_FRAME_STACK_BUTTON_TOOLTIP = "Toggle Blizzard's framestack tooltip\n\n A very helpful tool for finding frame names for use with /move or /hide", -- Missing translation
	TOGGLE_MODIFIED_FRAMES_ONLY_BUTTON_TOOLTIP = "Show only modified frames", -- Missing translation
	TOGGLE_MOVERS_BUTTON_TOOLTIP = "Toggles all movers", -- Missing translation
	UNREGISTER_ALL_EVENTS = "Unregister all events", -- Missing translation
	UNSERIALIZE_FRAME_INVALID_FORMAT = "Formato invalido",
	UNSERIALIZE_FRAME_NAME_DIFFERS = "Nombre Importado marco difiere de destino de importación",
	UNSERIALIZE_PROFILE_COMPLETED = "Importado %i elemento(s) en perfil \"% s\"",
	UNSERIALIZE_PROFILE_NO_NAME = "No se encuentra el nombre del perfil",
	UNSUPPORTED_FRAME = "Marco no soportado: %s",
	UNSUPPORTED_TYPE = "tipo no soportado: %s",
	WIDTH = "Width", -- Missing translation
	X_OFFSET = "X offset", -- Missing translation
	Y_OFFSET = "Y offset" -- Missing translation
}

_G.MOVANY = MOVANY
